Repository Parsely/wp-parsely, pull requests merged in 2021-09, with the labels that each got.

#364 Fix cookie parsing -- values can contain equal signs
  build/admin-page.asset.php
  build/admin-page.js
  build/init-api.asset.php
  build/init-api.js
  build/recommended-widget.asset.php
  build/recommended-widget.js
  package-lock.json
  package.json
  src/js/lib/cookies/index.js
  src/js/lib/cookies/utils.js
  src/js/lib/personalization.js
  src/js/widgets/recommended/index.js
  tests/js/lib/personalization.test.js
  tests/js/unit/lib/cookies.test.js
Labels: [Status] Needs Review

#369 Wrap post list links in an opt-in filter
  src/class-parsely.php
Labels: [Status] Needs Review

#370 Fix repeated metas notices
  src/class-parsely.php
  views/repeated-metas.php
Labels: [Status] Needs Review

#378 Release 2.5.2
  .github/workflows/cs-lint.yml
  .phpcs.xml.dist
  CHANGELOG.md
  README.md
  build/admin-page.asset.php
  build/admin-page.js
  build/init-api.asset.php
  build/init-api.js
  build/recommended-widget.asset.php
  build/recommended-widget.js
  composer.json
  package-lock.json
  package.json
  phpunit.xml.dist
  src/class-parsely-recommended-widget.php
  src/class-parsely.php
  src/js/lib/cookies/index.js
  src/js/lib/cookies/utils.js
  src/js/lib/personalization.js
  src/js/widgets/recommended/index.js
  src/parsely-settings.php
  tests/GetCurrentUrlTest.php
  tests/Integrations/AmpTest.php
  tests/Integrations/FbiaTest.php
  tests/OtherTest.php
  tests/StructuredData/AuthorArchiveTest.php
  tests/StructuredData/BlogArchiveTest.php
  tests/StructuredData/HomePageTest.php
  tests/StructuredData/NonPostTestCase.php
  tests/StructuredData/SinglePageTest.php
  tests/StructuredData/SinglePostTest.php
  tests/StructuredData/TermArchiveTest.php
  tests/TestCase.php
  tests/bootstrap.php
  tests/class-all-test.php
  tests/js/lib/personalization.test.js
  tests/js/unit/lib/cookies.test.js
  tests/recommended-api-test.php
  tests/structured-data/class-archive-post-test.php
  tests/structured-data/class-single-post-test.php
  views/repeated-metas.php
  wp-parsely.php
Labels: [Status] Needs Review

#380 Bring develop up to date with 2.5.2
  CHANGELOG.md
  README.md
Labels: [Status] Needs Review

#382 Simplifying get_options function
  src/class-parsely.php
Labels: Type: Maintenance, [Status] Needs Review

#383 Tests: Improve the get_current_url data provider
  tests/GetCurrentUrlTest.php
Labels: Type: Maintenance, [Status] Needs Review

#384 Tests: Rename final *-test.php file to *Test.php
  phpunit.xml.dist
  tests/RecommendedApiTest.php
Labels: Type: Maintenance

#360 Leverage the WordPress e2e testing framework to run end-to-end tests against the plugin
  .eslintrc
  .github/workflows/e2e-tests.yml
  .gitignore
  package-lock.json
  package.json
  tests/e2e/README.md
  tests/e2e/docker-compose.yml
  tests/e2e/init-e2e.sh
  tests/e2e/specs/activation-flow.spec.js
Labels: [Status] Needs Review

#385 Remove jQuery from Recommended Widget
  build/admin-page.asset.php
  build/admin-page.js
  build/init-api.asset.php
  build/init-api.js
  build/recommended-widget.asset.php
  build/recommended-widget.js
  package-lock.json
  src/class-parsely-recommended-widget.php
  src/js/widgets/recommended/index.js
  tests/e2e/specs/activation-flow.spec.js
Labels: Type: Maintenance, [Status] Needs Review

#388 Using npm caching on GitHub Actions
  .github/workflows/node.js.yml
Labels: [Status] Needs Review

#391 Remove unused return_personalized_json function
  src/class-parsely.php
Labels: Type: Maintenance, [Status] Needs Review

#345 Integrations: Extract into separate classes
  src/Integrations/class-amp.php
  src/Integrations/class-facebook-instant-articles.php
  src/Integrations/class-integration.php
  src/Integrations/class-integrations.php
  src/class-parsely.php
  tests/Integrations/AmpTest.php
  tests/Integrations/FacebookInstantArticlesTest.php
  tests/Integrations/FbiaTest.php
  tests/Integrations/IntegrationsTest.php
  tests/bootstrap.php
  wp-parsely.php
Labels: Type: Maintenance

#374 Add a step to the node CI test to confirm built scripts are included in the change
  .github/workflows/node.js.yml
Labels: [Status] Needs Review

#392 Hide admin warning on network admin
  src/class-parsely.php
  tests/OtherTest.php
  tests/TestCase.php
Labels: [Status] Needs Review

#398 Improving reliability of get_current_url tests
  tests/GetCurrentUrlTest.php
Labels: [Status] Needs Review

#397 Fix rendering errors when rendering multiple recommendation widgets
  build/recommended-widget.asset.php
  build/recommended-widget.js
  src/class-parsely-recommended-widget.php
  src/js/widgets/recommended/index.js
  wp-parsely.css
Labels: [Status] Needs Review

#400 Adding 3.0 upgrade notice on README
  README.md
Labels: [Status] Needs Review

#401 Split out plugin actions links logic
  src/UI/class-plugins-actions.php
  src/class-parsely.php
  tests/UI/PluginsActionsTest.php
  wp-parsely.php
Labels: Type: Maintenance

#403 Add e2e test for the plugin action link
  tests/e2e/README.md
  tests/e2e/specs/plugin-action-link.spec.js
Labels: Type: Maintenance

#405 Testcase: Allow getMethod() to use different class
  tests/TestCase.php
Labels: Type: Maintenance

#404 API Key: Add utility method for checking it is set
  src/class-parsely.php
  tests/OtherTest.php
Labels: Type: Maintenance

#409 Using utility function to check for API keys
  src/class-parsely.php
Labels: Type: Maintenance, [Status] Needs Review

#408 Add admin warning for minimum requirements in 3.0
  src/class-parsely.php
Labels: [Status] Needs Review

#415 Bring develop up to date with 2.6.0
  CHANGELOG.md
  README.md
  wp-parsely.php
Labels: Type: Maintenance, [Status] Needs Review

#416 Increase minimum PHP and WP versions
  .github/workflows/integration-tests.yml
  .github/workflows/unit-tests.yml
  .phpcs.xml.dist
  CONTRIBUTING.md
  README.md
  composer.json
  wp-parsely.php
Labels: Type: Maintenance

#420 Add strict_types=1 declaration
  CONTRIBUTING.md
  src/Integrations/class-amp.php
  src/Integrations/class-facebook-instant-articles.php
  src/Integrations/class-integration.php
  src/Integrations/class-integrations.php
  src/UI/class-plugins-actions.php
  src/UI/class-row-actions.php
  src/class-parsely-recommended-widget.php
  src/class-parsely.php
  src/parsely-settings.php
  tests/Integration/GetCurrentUrlTest.php
  tests/Integration/Integrations/AmpTest.php
  tests/Integration/Integrations/FacebookInstantArticlesTest.php
  tests/Integration/Integrations/IntegrationsTest.php
  tests/Integration/OtherTest.php
  tests/Integration/RecommendedApiTest.php
  tests/Integration/StructuredData/AuthorArchiveTest.php
  tests/Integration/StructuredData/BlogArchiveTest.php
  tests/Integration/StructuredData/HomePageTest.php
  tests/Integration/StructuredData/NonPostTestCase.php
  tests/Integration/StructuredData/SinglePageTest.php
  tests/Integration/StructuredData/SinglePostTest.php
  tests/Integration/StructuredData/TermArchiveTest.php
  tests/Integration/TestCase.php
  tests/Integration/UI/PluginsActionsTest.php
  tests/Integration/bootstrap.php
  tests/StructuredData/CustomPostTypeArchiveTest.php
  tests/StructuredData/CustomTaxonomyTermArchiveTest.php
  tests/UI/PluginsActionsTest.php
  tests/UI/RowActionsTest.php
  tests/Unit/Integrations/IntegrationsTest.php
  tests/Unit/bootstrap.php
  views/custom-metadata.php
  views/json-ld.php
  views/repeated-metas.php
  wp-parsely.php
Labels: Type: Maintenance

#419 CI: Specify coverage: none where it is not needed
  .github/workflows/integration-tests.yml
  .github/workflows/unit-tests.yml
Labels: Type: Maintenance

#417 Remove post_has_viewable_type
  src/UI/class-row-actions.php
  src/class-parsely.php
  tests/UI/RowActionsTest.php
Labels: [Status] Needs Review

#421 Using PHP 7 null coalescing operator
  src/class-parsely-recommended-widget.php
  src/class-parsely.php
Labels: Type: Maintenance
