Repository Parsely/wp-parsely, pull requests merged in 2021-12, with the labels that each got.

#526 Adding explicit dependabot reviewers
  .github/dependabot.yml
Labels: Type: Enhancement

#525 Adding instructions for local development on README files
  .github/pull_request_template.md
  CONTRIBUTING.md
  README.md
  tests/e2e/README.md
Labels: Type: Enhancement

#528 Adding E2E test to verify if scripts are rendered in FE
  tests/e2e/specs/front-end-code.spec.js
  tests/e2e/utils.js
Labels: Type: Enhancement

#527 Enabling linting for JS and CSS files
  .eslintrc
  .github/workflows/node.js.yml
  CONTRIBUTING.md
  README.md
  babel.config.js
  package-lock.json
  package.json
  tests/e2e/specs/front-end-code.spec.js
  tests/e2e/specs/recommended-widget.spec.js
  tests/e2e/utils.js
  wp-parsely.css
Labels: Type: Enhancement, Component: JavaScript

#445 Upgrading Ubuntu CI to 20.04
  .github/workflows/codeql-analysis.yml
  .github/workflows/cs-lint.yml
  .github/workflows/deploy.yml
  .github/workflows/e2e-tests.yml
  .github/workflows/integration-tests.yml
  .github/workflows/node.js.yml
  .github/workflows/unit-tests.yml
Labels: Type: Enhancement

#518 Settings Page UI improvements
  build/admin-page.asset.php
  build/admin-page.js
  src/UI/class-settings-page.php
  src/js/lib/admin-page/index.js
  views/parsely-settings.php
  webpack.config.js
Labels: Type: Enhancement

#519 Hide Disable AMP setting when AMP plugin is not enabled
  src/UI/class-settings-page.php
Labels: Type: Enhancement

#537 docs: Fix typo in example for PHP code standard
  CONTRIBUTING.md
Labels: Type: Documentation, [Status] Needs Review

#539 Update package-lock.json -- tabs vs. spaces
  package-lock.json
Labels: [Status] Needs Review

#545 Source the correct asset meta data file for the Recommendations Widget
  src/UI/class-recommended-widget.php
Labels: Type: Bug

#538 Leverage Husky to enforce linters and coding standards prior to commit
  .husky/pre-commit
  CONTRIBUTING.md
  package-lock.json
  package.json
  src/UI/class-settings-page.php
  src/class-parsely.php
  src/class-scripts.php
  tests/Integration/ScriptsTest.php
Labels: Type: Maintenance, [Status] Needs Review, Component: Dependencies

#489 Adding decoupled support
  src/class-rest.php
  tests/Integration/RestTest.php
  wp-parsely.php
Labels: Type: Enhancement

#552 Improve settings page texts
  src/UI/class-settings-page.php
Labels: [Status] Needs Review

#561 Correct Parsely spelling in comments within tests
  tests/Integration/OtherTest.php
  tests/Integration/StructuredData/AuthorArchiveTest.php
  tests/Integration/StructuredData/BlogArchiveTest.php
  tests/Integration/StructuredData/CustomPostTypeArchiveTest.php
  tests/Integration/StructuredData/CustomTaxonomyTermArchiveTest.php
  tests/Integration/StructuredData/HomePageTest.php
  tests/Integration/StructuredData/SinglePageTest.php
  tests/Integration/StructuredData/SinglePostTest.php
  tests/Integration/StructuredData/TermArchiveTest.php
Labels: [Status] Needs Review

#559 CI: Add concurrency to CI configs, and Composer tweaks
  .github/workflows/codeql-analysis.yml
  .github/workflows/cs-lint.yml
  .github/workflows/integration-tests.yml
  .github/workflows/node.js.yml
  .github/workflows/unit-tests.yml
  composer.json
Labels: Type: Maintenance
