Repository Parsely/wp-parsely, pull requests merged in 2021-11, with the labels that each got.

#467 Extract settings page from Parsely class
  src/UI/class-plugins-actions.php
  src/UI/class-settings-page.php
  src/class-parsely.php
  views/parsely-settings.php
  wp-parsely.php
Labels: Type: Maintenance, [Status] Needs Review

#474 Fix type errors
  src/class-parsely-recommended-widget.php
  src/class-parsely.php
Labels: Type: Maintenance, [Status] Needs Review

#475 Adding namespace to Recommended Widget
  src/UI/class-recommended-widget.php
  tests/Integration/RecommendedApiTest.php
  uninstall.php
  views/parsely-settings.php
  wp-parsely.php
Labels: Type: Maintenance, [Status] Needs Review

#473 Adding filter to display Cloudflare links
  README.md
  src/class-parsely.php
  tests/Integration/OtherTest.php
Labels: Type: Enhancement, [Status] Needs Review

#460 Avoid making duplicate calls on Recommended Widget
  build/recommended-widget.asset.php
  build/recommended-widget.js
  src/UI/class-recommended-widget.php
  src/js/widgets/recommended/index.js
  tests/e2e/specs/activation-flow.spec.js
  tests/e2e/specs/recommended-widget.spec.js
  tests/e2e/utils.js
Labels: Type: Maintenance, [Status] Needs Review

#468 Extract admin warning from class-parsely
  src/UI/class-admin-warning.php
  src/class-parsely.php
  tests/Integration/OtherTest.php
  tests/Integration/UI/AdminWarningTest.php
  wp-parsely.php
Labels: Type: Maintenance, [Status] Needs Review

#476 e2e tests: fix watch command
  package.json
Labels: Type: Bug, Type: Maintenance

#477 Adding namespace to root class
  src/Integrations/class-amp.php
  src/Integrations/class-facebook-instant-articles.php
  src/UI/class-admin-warning.php
  src/UI/class-plugins-actions.php
  src/UI/class-recommended-widget.php
  src/UI/class-row-actions.php
  src/UI/class-settings-page.php
  src/class-parsely.php
  tests/Integration/GetCurrentUrlTest.php
  tests/Integration/Integrations/AmpTest.php
  tests/Integration/Integrations/FacebookInstantArticlesTest.php
  tests/Integration/Integrations/IntegrationsTest.php
  tests/Integration/OtherTest.php
  tests/Integration/RecommendedApiTest.php
  tests/Integration/StructuredData/AuthorArchiveTest.php
  tests/Integration/StructuredData/BlogArchiveTest.php
  tests/Integration/StructuredData/CustomPostTypeArchiveTest.php
  tests/Integration/StructuredData/CustomTaxonomyTermArchiveTest.php
  tests/Integration/StructuredData/HomePageTest.php
  tests/Integration/StructuredData/SinglePageTest.php
  tests/Integration/StructuredData/SinglePostTest.php
  tests/Integration/StructuredData/TermArchiveTest.php
  tests/Integration/TestCase.php
  tests/Integration/UI/AdminWarningTest.php
  tests/Integration/UI/PluginsActionsTest.php
  tests/Integration/UI/RowActionsTest.php
  views/custom-metadata.php
  views/json-ld.php
  views/parsely-settings.php
  views/repeated-metas.php
  wp-parsely.php
Labels: Type: Maintenance, [Status] Needs Review

#482 Use checkboxes for multiple selects in settings page
  src/UI/class-settings-page.php
Labels: Type: Enhancement, [Status] Needs Review

#478 Move tracker logic to separate file
  src/class-parsely.php
  src/class-scripts.php
  tests/Integration/OtherTest.php
  tests/Integration/ScriptsTest.php
  wp-parsely.php
Labels: Type: Maintenance, [Status] Needs Review

#481 Renaming functions on Scripts class
  src/class-scripts.php
  tests/Integration/ScriptsTest.php
Labels: Type: Maintenance, [Status] Needs Review

#493 Adding a cannonical way of running the plugin locally
  .nvmrc
  README.md
  package-lock.json
  package.json
Labels: Type: Enhancement, [Status] Needs Review

#486 Making class members private
  src/Integrations/class-amp.php
  src/Integrations/class-facebook-instant-articles.php
  src/UI/class-recommended-widget.php
  tests/Integration/Integrations/FacebookInstantArticlesTest.php
  tests/Integration/RecommendedApiTest.php
Labels: Type: Maintenance, [Status] Needs Review

#495 Adding changelog for 3.0.0
  CHANGELOG.md
Labels: [Status] Needs Review

#494 Remove unnecessary npm step in e2e
  .github/workflows/e2e-tests.yml
  tests/e2e/README.md
  tests/e2e/specs/activation-flow.spec.js
  tests/e2e/specs/plugin-action-link.spec.js
  tests/e2e/specs/recommended-widget.spec.js
  tests/e2e/utils.js
Labels: Type: Enhancement, [Status] Needs Review

#499 Running Node JS checks with latest version only
  .github/workflows/node.js.yml
Labels: [Status] Needs Review

#498 Checking for updates in GitHub Actions
  .github/dependabot.yml
Labels: Type: Enhancement, [Status] Needs Review

#505 Bring develop up to date with 3.0.0
  CHANGELOG.md
  README.md
  src/UI/class-recommended-widget.php
  wp-parsely.php
Labels: [Status] Needs Review

#506 Changelog: Add more detail for 3.0 release
  CHANGELOG.md
Labels: Type: Documentation

#507 Release 3.0.0 beta 2
  .github/dependabot.yml
  .github/workflows/e2e-tests.yml
  .github/workflows/node.js.yml
  CHANGELOG.md
  README.md
  tests/e2e/README.md
  tests/e2e/specs/activation-flow.spec.js
  tests/e2e/specs/plugin-action-link.spec.js
  tests/e2e/specs/recommended-widget.spec.js
  tests/e2e/utils.js
  wp-parsely.php
Labels: [Status] Needs Review

#508 Deploy on published release
  .github/workflows/deploy.yml
Labels: Type: Maintenance

#510 Making sure the coauthors plugin returns a WP_User
  src/class-parsely.php
Labels: [Status] Needs Review

#504 Adding types to function arguments in GetCurrentUrlTest
  tests/Integration/GetCurrentUrlTest.php
Labels: Type: Maintenance, [Status] Needs Review

#513 Settings page: Use submit_button() function
  views/parsely-settings.php
Labels: Type: Maintenance

#514 Docs: Minor amendments
  README.md
Labels: Type: Documentation

#502 Removing version leak in front-end
  src/class-parsely.php
Labels: Type: Enhancement, [Status] Needs Review

#511 Tests: Run in random order
  composer.json
Labels: Type: Maintenance

#512 PR Template: Remove checkboxes
  .github/pull_request_template.md
Labels: Type: Maintenance

#496 Remove custom admin CSS
  src/UI/class-settings-page.php
  views/parsely-settings.php
Labels: Type: Maintenance, [Status] Needs Review

#521 Fixing end to end tests in CI
  .github/workflows/deploy.yml
  .github/workflows/e2e-tests.yml
Labels: [Status] Needs Review

#523 Removing PHP 8.2 from CI
  .github/workflows/integration-tests.yml
Labels: [Status] Needs Review

#517 Bug fix: multiple checkboxes labels
  src/UI/class-settings-page.php
Labels: Type: Bug
