Repository Parsely/wp-parsely, pull requests merged in 2021-05, with the labels that each got.

#273 Convert Profile API call to simple XHR - no more JSONP
  build/admin-page.asset.php
  build/admin-page.js
  build/init-api.asset.php
  build/init-api.js
  src/js/lib/init-api/index.js
Labels: [Status] Needs Review

#267 Widget: Add missing translator comment
  src/class-parsely-recommended-widget.php
Labels: Type: Maintenance

#274 Fix CSS file URL path
  src/class-parsely.php
  wp-parsely.php
Labels: Type: Bug, [Status] Needs Review

#236 Pull Scripts out of PHP & Begin removing jQuery dependency
  .gitattributes
  .gitignore
  .nvmrc
  DEVELOP.md
  build/admin-page.asset.php
  build/admin-page.js
  build/init-api.asset.php
  build/init-api.js
  package-lock.json
  package.json
  phpunit.xml.dist
  src/class-parsely-recommended-widget.php
  src/class-parsely.php
  src/index.js
  src/js/lib/admin-page/index.js
  src/js/lib/init-api/index.js
  src/parsely-admin-header.php
  tests/class-all-test.php
  tests/testcase.php
  wp-parsely.php
Labels: [Status] Needs Review

#269 Composer: Normalize and improve composer.json
  .github/workflows/integration-tests.yml
  composer.json
Labels: Type: Maintenance

#268 i18n: Load plugin text domain
  wp-parsely.php
Labels: Type: Enhancement

#271 Change $post to $parsely_type
  src/class-parsely.php
Labels: Type: Maintenance

#276 Fix Path to PHP Views
  src/class-parsely.php
  wp-parsely.php
Labels: Type: Bug, [Status] Needs Review

#278 Simplify PHP Main Entry File
  wp-parsely.php
Labels: [Status] Needs Review

#275 Add Pull Request Template & Issue Templates for Bug Reports & Feature Requests
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
Labels: Type: Maintenance, [Status] Needs Review

#282 Fix The Plugin Action Link
  src/class-parsely.php
  wp-parsely.php
Labels: [Status] Needs Review

#284 Remove src/parsely-javascript.php
  src/parsely-javascript.php
Labels: Type: Maintenance

#287 Add Dependabot Reviewers
  .github/dependabot.yml
Labels: Type: Maintenance

#266 Update the Plugin Version to 2.5.0-alpha & generalize the version test
  README.md
  package-lock.json
  package.json
  src/class-parsely.php
  tests/class-all-test.php
  wp-parsely.php
Labels: Type: Maintenance, [Status] Needs Review

#286 Add data-cfasync="false" to script tags
  src/class-parsely.php
  tests/class-all-test.php
Labels: [Status] Needs Review

#270 Add filter wp_parsely_post_type for NewsArticle
  src/class-parsely.php
  tests/class-all-test.php
  tests/testcase.php
Labels: [Status] Needs Review

#297 JS Unit Testing Framework & coverage for cookie lib
  build/recommended-widget.asset.php
  build/recommended-widget.js
  package.json
  src/js/lib/cookies/index.js
  src/js/lib/cookies/utils.js
  tests/js/unit/lib/cookies.test.js
Labels: Type: Maintenance, [Status] Needs Review, javascript

#298 Improve widget js dir structure
  build/recommended-widget.asset.php
  package.json
  src/js/widgets/recommended/index.js
  webpack.config.js
Labels: Type: Maintenance, [Status] Needs Review, javascript

#281 Refactor JavaScript Registration & Loading. Add Consistency to Filter Names
  README.md
  src/class-parsely.php
  tests/class-all-test.php
Labels: [Status] Needs Review

#313 Composer: Add composer/installers
  composer.json
Labels: Type: Maintenance

#315 CI: Use Ubuntu 18.04
  .github/workflows/integration-tests.yml
Labels: Type: Maintenance

#317 Release 2.5.0
  .gitattributes
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/release-template.md
  .github/dependabot.yml
  .github/pull_request_template.md
  .github/workflows/deploy.yml
  .github/workflows/integration-tests.yml
  .github/workflows/node.js.yml
  .gitignore
  .nvmrc
  .wordpress-org/screenshot-1.png
  .wordpress-org/screenshot-2.png
  .wordpress-org/screenshot-3.png
  .wordpress-org/screenshot-4.png
  CHANGELOG.md
  CONTRIBUTING.md
  DEVELOP.md
  README.md
  bin/export-plugin.sh
  build/admin-page.asset.php
  build/admin-page.js
  build/init-api.asset.php
  build/init-api.js
  build/recommended-widget.asset.php
  build/recommended-widget.js
  class-parsely-recommended-widget.php
  composer.json
  package-lock.json
  package.json
  parsely-admin-header.php
  parsely-javascript.php
  parsely-parsely-page.php
  phpunit.xml.dist
  src/class-parsely-recommended-widget.php
  src/class-parsely.php
  src/index.js
  src/js/lib/admin-page/index.js
  src/js/lib/cookies/index.js
  src/js/lib/cookies/utils.js
  src/js/lib/init-api/index.js
  src/js/widgets/recommended/index.js
  src/parsely-settings.php
  tests/all-test.php
  tests/bootstrap.php
  tests/class-all-test.php
  tests/js/unit/lib/cookies.test.js
  tests/recommended-api-test.php
  tests/structured-data/class-archive-post-test.php
  tests/structured-data/class-single-non-post-test.php
  tests/structured-data/class-single-post-test.php
  tests/testcase.php
  views/custom-metadata.php
  views/json-ld.php
  views/repeated-metas.php
  webpack.config.js
  wp-parsely.php
Labels: [Status] Needs Review
