Repository Parsely/wp-parsely, pull requests merged in 2021-10, with the labels that each got.

#429 Add return type declarations
  src/Integrations/class-amp.php
  src/Integrations/class-facebook-instant-articles.php
  src/Integrations/class-integration.php
  src/Integrations/class-integrations.php
  src/UI/class-plugins-actions.php
  src/UI/class-row-actions.php
  src/class-parsely-recommended-widget.php
  src/class-parsely.php
  tests/Integration/GetCurrentUrlTest.php
  tests/Integration/Integrations/AmpTest.php
  tests/Integration/Integrations/FacebookInstantArticlesTest.php
  tests/Integration/Integrations/IntegrationsTest.php
  tests/Integration/OtherTest.php
  tests/Integration/RecommendedApiTest.php
  tests/Integration/StructuredData/AuthorArchiveTest.php
  tests/Integration/StructuredData/BlogArchiveTest.php
  tests/Integration/StructuredData/HomePageTest.php
  tests/Integration/StructuredData/NonPostTestCase.php
  tests/Integration/StructuredData/SinglePageTest.php
  tests/Integration/StructuredData/SinglePostTest.php
  tests/Integration/StructuredData/TermArchiveTest.php
  tests/Integration/TestCase.php
  tests/Integration/UI/PluginsActionsTest.php
  tests/StructuredData/CustomPostTypeArchiveTest.php
  tests/StructuredData/CustomTaxonomyTermArchiveTest.php
  tests/UI/PluginsActionsTest.php
  tests/UI/RowActionsTest.php
  tests/Unit/Integrations/IntegrationsTest.php
  wp-parsely.php
Labels: Type: Maintenance

#431 Minor code fixes
  src/Integrations/class-amp.php
  src/Integrations/class-facebook-instant-articles.php
  src/Integrations/class-integrations.php
  src/class-parsely-recommended-widget.php
  src/class-parsely.php
  tests/Integration/Integrations/FacebookInstantArticlesTest.php
  tests/Integration/TestCase.php
  tests/Integration/bootstrap.php
  wp-parsely.php
Labels: Type: Maintenance

#427 Tests: Stop using deprecated setMethods method
  tests/Unit/Integrations/IntegrationsTest.php
Labels: Type: Maintenance

#436 Remove deprecated filter after_set_parsely_page
  src/class-parsely.php
  tests/Integration/OtherTest.php
Labels: Type: Maintenance, [Status] Needs Review

#437 Remove deprecated filter parsely_filter_insert_javascript
  src/class-parsely.php
  tests/Integration/OtherTest.php
Labels: Type: Maintenance, [Status] Needs Review

#439 Fix non-working README code sample
  README.md
Labels: Type: Maintenance, [Status] Needs Review

#446 Fixing return types of update_metadata_endpoint
  src/class-parsely.php
Labels: Type: Maintenance, [Status] Needs Review

#452 Release 2.6.1
  CHANGELOG.md
  README.md
  wp-parsely.php
Labels: [Status] Needs Review

#430 Add namespaces to files
  src/UI/class-plugins-actions.php
  src/class-parsely-recommended-widget.php
  src/class-parsely.php
  tests/Integration/Integrations/IntegrationsTest.php
  tests/Integration/OtherTest.php
  tests/Integration/RecommendedApiTest.php
  tests/Integration/StructuredData/CustomPostTypeArchiveTest.php
  tests/Integration/StructuredData/CustomTaxonomyTermArchiveTest.php
  tests/Integration/UI/PluginsActionsTest.php
  tests/Integration/UI/RowActionsTest.php
  tests/Integration/bootstrap.php
  tests/UI/PluginsActionsTest.php
  tests/Unit/bootstrap.php
  wp-parsely.php
Labels: Type: Maintenance
