Repository Parsely/wp-parsely, pull requests merged in 2021-04, with the labels that each got.

#165 Add LICENSE file
  LICENSE
  composer.json
Labels: Type: maintenance

#167 Add .editorconfig file
  .editorconfig
Labels: Type: maintenance

#170 Add documentation to hooks
  class-parsely-recommended-widget.php
  wp-parsely.php
Labels: Type: maintenance

#173 CI: Migrate Travis CI to GitHub Action workflow
  .github/workflows/ci.yml
  .travis.yml
  composer.json
Labels: Priority: High, Type: maintenance

#183 Simple JS WP build env + prettier & eslint
  .eslintrc
  .gitignore
  .prettierrc
  package.json
  src/index.js
Labels: [Status] Needs Review

#185 Add CODEOWNERS file
  .github/CODEOWNERS
Labels: Type: maintenance

#154 CS: Add coding standards checks
  .phpcs.xml.dist
  composer.json
Labels: Type: maintenance, [Status] Ready to Merge

#166 Add .gitattributes file
  .gitattributes
Labels: Type: maintenance, [Status] Ready to Merge

#178 CI: Allow Composer validation to fail
  .github/workflows/ci.yml
Labels: Type: maintenance

#153 Tests: Refresh scaffolded plugin test files
  bin/install-wp-tests.sh
  tests/bootstrap.php
Labels: Type: maintenance

#188 Improve WordPress.org support
  .wordpress-org/icon-128x128.png
  .wordpress-org/icon-256x256.png
  .wordpress-org/screenshot-1.png
  .wordpress-org/screenshot-2.png
  .wordpress-org/screenshot-3.png
  .wordpress-org/screenshot-4.png
  CHANGELOG.md
  README.md
  readme.txt
  screenshot-3.png
  screenshot-4.png
Labels: Type: maintenance

#163 Widget: Move registration outside of widget file
  class-parsely-recommended-widget.php
  wp-parsely.php
Labels: Type: maintenance, [Status] Ready to Merge

#164 Widget: Fix displayed name and description
  class-parsely-recommended-widget.php
Labels: Type: maintenance, [Status] Ready to Merge

#197 Tests: Fix multisite tests not running
  .github/workflows/cs-lint.yml
  .github/workflows/integration-tests.yml
  composer.json
Labels: Type: maintenance

#162 Improve widget settings UI
  class-parsely-recommended-widget.php
Labels: [Status] Ready to Merge, enhancement

#195 Adjust plugins headers
  wp-parsely.php
Labels: Type: maintenance

#171 PHP: Specify minimum version
  README.md
  composer.json
Labels: Type: maintenance, [Status] Ready to Merge

#202 Don't give metadata output for is_search()
  wp-parsely.php
Labels: enhancement

#199 Changelog for wp-parsely 2.4.0
  CHANGELOG.md
Labels: Type: maintenance

#207 Tests: Call the TestCase factory method statically
  tests/structured-data/archive-post-test.php
  tests/structured-data/single-non-post-test.php
  tests/structured-data/single-post-test.php
Labels: [Status] Needs Review

#226 Translations: Internationalize strings in PHP
  class-parsely-recommended-widget.php
  parsely-settings.php
  wp-parsely.php
Labels: enhancement

#205 Widget: Replace form and hide front-end output when API settings are missing
  class-parsely-recommended-widget.php
Labels: [Status] Needs Rebase, enhancement

#232 Better load Widget CSS and use plugin version for cache busting
  class-parsely-recommended-widget.php
  wp-parsely.php
Labels: enhancement

#238 Stop Using Protocol-Relative URL for Tracking Script
  parsely-javascript.php
  tests/all-test.php
  wp-parsely.php
Labels: [Status] Needs Review

#203 Widget: allow no boost to Recommendation widget
  class-parsely-recommended-widget.php
  tests/recommended-api-test.php
Labels: enhancement

#204 Add $post_id to wp_parsely_permalink filter hook
  wp-parsely.php
Labels: enhancement

#233 CI: Use matrix PHP version
  .github/workflows/integration-tests.yml
Labels: Type: maintenance

#234 CI: Small improvements
  .github/workflows/integration-tests.yml
Labels: Type: maintenance

#250 Docs: Add missing change log link
  CHANGELOG.md
Labels: Type: maintenance

#251 Admin page: Improve page title
  parsely-settings.php
Labels: bug

#253 Admin page: Improve accessibility of radio inputs
  parsely-admin-header.php
  wp-parsely.php
Labels: enhancement

#216 Docs: Remove HTML from screenshot caption
  README.md
Labels: Type: maintenance

#217 Docs: Use standard markdown for code block
  README.md
Labels: Type: maintenance

#242 Support Custom Post Status Slugs
  wp-parsely.php
Labels: [Status] Needs Review

#257 Metadata: Move output into views
  parsely-parsely-page.php
  views/custom-metadata.php
  views/json-ld.php
  views/repeated-metas.php
  wp-parsely.php
Labels: Type: maintenance

#258 Prevent Unit Tests from echoing
  tests/all-test.php
Labels: Type: maintenance

#261 Test Files: Update code style
  tests/bootstrap.php
  tests/class-all-test.php
  tests/structured-data/class-archive-post-test.php
  tests/structured-data/class-single-non-post-test.php
  tests/structured-data/class-single-post-test.php
  tests/testcase.php
Labels: [Status] Needs Review

#263 Docs: Replace incorrect feature
  README.md
Labels: Type: Documentation

#262 Rename the main class file to class-parsely.php & source it in the plugin entry file
  src/class-parsely-recommended-widget.php
  src/class-parsely.php
  src/parsely-admin-header.php
  src/parsely-javascript.php
  src/parsely-settings.php
  wp-parsely.php
Labels: [Status] Needs Review

#235 Use strict code coverage and add code coverage output
  .github/workflows/integration-tests.yml
  .gitignore
  composer.json
  phpunit.xml.dist
  tests/class-all-test.php
  tests/recommended-api-test.php
  tests/structured-data/class-archive-post-test.php
  tests/structured-data/class-single-non-post-test.php
  tests/structured-data/class-single-post-test.php
Labels: Type: Maintenance, [Status] Needs Review
