Repository Parsely/wp-parsely, pull requests merged in 2022-11, with the labels that each got.

#1160 README.md: Update "Tested up to" to 6.1.0
  README.md
Labels: Type: Maintenance, Changelog: Skip

#1159 Metadata Author Archive Builder: Add support for the Co-Authors Plus plugin
  src/Metadata/class-author-archive-builder.php
  tests/Integration/Metadata/AuthorArchiveTest.php
Labels: Changelog: Added

#1181 Add composer phpcbf script for automatically fixing PHPCS errors
  CONTRIBUTING.md
  composer.json
Labels: Changelog: Added

#1179 Archive Pages: Improve headline metadata by using date format provided by site settings
  src/Metadata/class-date-builder.php
  tests/Integration/Metadata/DateArchiveTest.php
Labels: Changelog: Changed

#1182 Integration Tests: Replace the deprecated this->factory with self::factory()
  tests/Integration/Metadata/SinglePostTest.php
  tests/Integration/OtherTest.php
  tests/Integration/TestCase.php
  tests/Integration/UI/NetworkAdminSitesListTest.php
  tests/Integration/UI/SettingsPageTest.php
Labels: Changelog: Changed

#1195 Avoid tracking page views when post is opened in preview mode
  src/class-scripts.php
  tests/Integration/ScriptsTest.php
  tests/Integration/TestCase.php
Labels: Changelog: Fixed

#1207 Refactoring: Adds helper methods to check script statuses
  tests/Integration/ScriptsTest.php
Labels: Changelog: Skip

#1216 Content Helper: Updated UI of Related Top Performing Posts
  build/content-helper.asset.php
  build/content-helper.css
  build/content-helper.js
  src/blocks/content-helper/components/related-top-post-list-item.tsx
  src/blocks/content-helper/components/related-top-post-list.tsx
  src/blocks/content-helper/content-helper-provider.ts
  src/blocks/content-helper/content-helper.scss
  src/blocks/content-helper/icons/published-link-icon.tsx
  src/blocks/content-helper/icons/views-icon.tsx
  src/blocks/shared/utils/date.ts
  src/blocks/shared/variables.scss
  src/class-parsely.php
  tests/e2e/specs/blocks/content-helper/filters.spec.js
  tests/e2e/utils.js
  tests/js/blocks/content-helper/structure.test.js
Labels: Changelog: Changed
