Repository Parsely/wp-parsely, pull requests merged in 2022-02, with the labels that each got.

#531 Add Screen Options to toggle settings sections
  src/UI/class-settings-page.php
  tests/e2e/specs/activation-flow.spec.js
  tests/e2e/utils.js
  uninstall.php
  views/parsely-settings.php
  wp-parsely.php
Labels: Type: Enhancement

#633 Settings page: Improve UI for post/page types to track
  build/admin-settings.asset.php
  build/admin-settings.css
  src/UI/class-settings-page.php
  src/css/admin-settings.css
  tests/Integration/UI/SettingsPageTest.php
  tests/e2e/specs/activation-flow.spec.js
  tests/e2e/specs/settings-track-post-types-as.js
  tests/e2e/utils.js
  webpack.config.js
Labels: [Status] Needs Review

#668 Allow settings to be saved when "Requires recrawl" section is hidden
  src/UI/class-settings-page.php
  tests/Integration/UI/SettingsPageTest.php
  tests/e2e/specs/settings-track-post-types-as.js
Labels: [Status] Needs Review

#676 Update some outdated references in function comments
  src/class-dashboard-link.php
  tests/Integration/DashboardLinkTest.php
  tests/Integration/UI/RowActionsTest.php
Labels: [Status] Needs Review

#654 Improve documentation
  CONTRIBUTING.md
  WINDOWS.md
Labels: Type: Documentation

#680 Fix integration test on Windows
  views/repeated-metas.php
Labels: [Status] Needs Review
