Repository Parsely/wp-parsely, pull requests merged in 2022-09, with the labels that each got.

#985 Switch to Composer autoloader
  .github/workflows/deploy.yml
  .github/workflows/e2e-tests.yml
  composer.json
  wp-parsely.php
Labels: Changelog: Changed

#1077 Content Helper: Fix broken links in "Post Stats" button
  build/content-helper.asset.php
  build/content-helper.js
  src/@types/index.d.ts
  src/Endpoints/class-analytics-posts-api-proxy.php
  src/Endpoints/class-base-api-proxy.php
  src/blocks/content-helper/content-helper-provider.ts
  tests/Integration/Endpoints/AnalyticsPostsProxyEndpointTest.php
Labels: Changelog: Skip

#1080 Release wp-parsely 3.5.1
  CHANGELOG.md
  README.md
  build/content-helper.asset.php
  build/content-helper.js
  package-lock.json
  package.json
  src/@types/index.d.ts
  src/Endpoints/class-analytics-posts-api-proxy.php
  src/Endpoints/class-base-api-proxy.php
  src/blocks/content-helper/content-helper-provider.ts
  tests/Integration/Endpoints/AnalyticsPostsProxyEndpointTest.php
  tests/e2e/utils.js
  wp-parsely.php
Labels: Changelog: Skip

#1071 Settings page: Update "Track logged-in users" option texts for clarity
  src/UI/class-metadata-renderer.php
  src/UI/class-settings-page.php
  src/class-parsely.php
  src/class-scripts.php
  tests/Integration/ScriptsTest.php
Labels: Changelog: Changed

#1081 Merge trunk into develop after the 3.5.1 release
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
  tests/e2e/utils.js
  wp-parsely.php
Labels: Changelog: Skip

#1082 README.md: Update "Tested up to" to 6.0.2
  README.md
Labels: Changelog: Skip

#1069 Content Helper: Refactor code for clarity
  build/content-helper.asset.php
  build/content-helper.js
  src/blocks/content-helper/components/related-top-post-list-item.tsx
  src/blocks/content-helper/components/related-top-post-list.tsx
  src/blocks/content-helper/content-helper-provider.ts
  src/blocks/content-helper/content-helper.tsx
  src/blocks/content-helper/models/function-results.ts
  src/blocks/content-helper/models/related-top-post-data.ts
  tests/e2e/utils.js
  tests/js/blocks/content-helper/structure.test.js
Labels: Changelog: Changed, Feature: Content Helper

#1098 Use Parsely->get_options() in the whole codebase
  src/Integrations/class-amp.php
  src/Integrations/class-facebook-instant-articles.php
  src/Integrations/class-google-web-stories.php
  src/Integrations/class-integration.php
  src/Integrations/class-integrations.php
  src/UI/class-recommended-widget.php
  tests/Integration/Integrations/AmpTest.php
  tests/Integration/Integrations/FacebookInstantArticlesTest.php
  tests/Integration/Integrations/GoogleWebStoriesTest.php
  tests/Integration/Integrations/IntegrationsTest.php
  tests/Integration/Metadata/SinglePostTest.php
  tests/Unit/Integrations/IntegrationsTest.php
  wp-parsely.php
Labels: Type: Maintenance, Type: Refactoring, Changelog: Changed

#1114 Content Helper: Show "Contact Us" message when Site ID or API Secret are not set
  build/content-helper.asset.php
  build/content-helper.css
  build/content-helper.js
  src/Endpoints/class-base-api-proxy.php
  src/blocks/content-helper/components/related-top-post-list.tsx
  src/blocks/content-helper/content-helper-provider.ts
  src/blocks/content-helper/content-helper.scss
  tests/Integration/ProxyEndpointTest.php
  tests/e2e/specs/blocks/content-helper/errors.spec.js
  tests/e2e/specs/blocks/content-helper/top-bar-icon.spec.js
Labels: Changelog: Changed

#1117 Release wp-parsely 3.5.2
  CHANGELOG.md
  README.md
  build/content-helper.asset.php
  build/content-helper.js
  package-lock.json
  package.json
  src/Endpoints/class-base-api-proxy.php
  src/Integrations/class-amp.php
  src/Integrations/class-facebook-instant-articles.php
  src/Integrations/class-google-web-stories.php
  src/Integrations/class-integration.php
  src/Integrations/class-integrations.php
  src/UI/class-recommended-widget.php
  src/blocks/content-helper/components/post-list.tsx
  src/blocks/content-helper/content-helper-provider.ts
  tests/Integration/Integrations/AmpTest.php
  tests/Integration/Integrations/FacebookInstantArticlesTest.php
  tests/Integration/Integrations/GoogleWebStoriesTest.php
  tests/Integration/Integrations/IntegrationsTest.php
  tests/Integration/Metadata/SinglePostTest.php
  tests/Integration/ProxyEndpointTest.php
  tests/Unit/Integrations/IntegrationsTest.php
  tests/e2e/specs/blocks/content-helper/errors.spec.js
  tests/e2e/specs/blocks/content-helper/top-bar-icon.spec.js
  tests/e2e/utils.js
  wp-parsely.php
Labels: Changelog: Skip

#1120 Merge trunk into develop after the 3.5.2 release
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
  tests/e2e/utils.js
  wp-parsely.php
Labels: Changelog: Skip
