Repository Parsely/wp-parsely, pull requests merged in 2022-01, with the labels that each got.

#500 Add parsely-meta-string field to REST API
  README.md
  src/class-rest.php
  tests/Integration/RestTest.php
Labels: Type: Enhancement

#557 Try to improve script integration tests
  tests/Integration/GetCurrentUrlTest.php
  tests/Integration/OtherTest.php
  tests/Integration/ScriptsTest.php
  tests/Integration/TestCase.php
Labels: [Status] Needs Review

#560 Resolve #558 (Last Modified date is wrong in the json+ld)
  src/class-parsely.php
  tests/Integration/StructuredData/SinglePostTest.php
Labels: [Status] Needs Review

#543 Settings page: Show error message when duplicate tracking selected
  src/UI/class-settings-page.php
  tests/Integration/UI/SettingsPageTest.php
Labels: [Status] Needs Review

#574 Update wordpress.org screenshots for settings page
  .wordpress-org/screenshot-1.png
  .wordpress-org/screenshot-2.png
  .wordpress-org/screenshot-3.png
  .wordpress-org/screenshot-4.png
  .wordpress-org/screenshot-5.png
  README.md
Labels: [Status] Needs Review

#581 Add wordpress.org banner images
  .wordpress-org/banner-1544x500.png
  .wordpress-org/banner-772x250.png
Labels: [Status] Needs Review

#569 Adding Parse.ly stats button on admin bar
  src/UI/class-admin-bar.php
  src/UI/class-row-actions.php
  src/class-dashboard-link.php
  tests/Integration/DashboardLinkTest.php
  tests/Integration/OtherTest.php
  tests/Integration/RestTest.php
  tests/Integration/UI/AdminBarTest.php
  tests/Integration/UI/AdminWarningTest.php
  tests/Integration/UI/RowActionsTest.php
  wp-parsely.php
Labels: [Status] Do not merge

#610 Update follow-redirects package to the latest version
  build/init-api.asset.php
  build/recommended-widget.asset.php
  package-lock.json
Labels: [Status] Needs Review

#613 Update CONTRIBUTING.md for clarity and readability
  CONTRIBUTING.md
Labels: [Status] Needs Review

#583 Show settings link & API Key in Network Admin sites list
  .github/workflows/integration-tests.yml
  src/UI/class-network-admin-sites-list.php
  src/class-parsely.php
  tests/Integration/UI/NetworkAdminSitesListTest.php
  tests/Integration/UI/SettingsPageTest.php
  wp-parsely.php
Labels: [Status] Needs Review

#619 Add a WINDOWS.md file for Windows developers
  CONTRIBUTING.md
  WINDOWS.md
Labels: Type: Documentation
