Repository Parsely/wp-parsely, pull requests merged in 2022-06, with the labels that each got.

#915 Fix failing Recommended Widget test
  tests/e2e/specs/recommended-widget.spec.js
Labels: Changelog: Changed

#926 Fix broken package.json
  package-lock.json
Labels: Type: Bug

#923 Fix some SonarCloud issues
  src/Metadata/class-post-builder.php
  src/UI/class-plugins-actions.php
  src/class-scripts.php
  tests/Integration/Endpoints/RelatedProxyEndpointTest.php
  tests/Integration/TestCase.php
Labels: Type: Maintenance, Changelog: Fixed

#941 CONTRIBUTING.md: Add note about svn
  CONTRIBUTING.md
Labels: Type: Documentation, Changelog: Changed

#937 Prepare README.md for 3.4.0 release
  .wordpress-org/screenshot-1.png
  .wordpress-org/screenshot-2.png
  .wordpress-org/screenshot-3.png
  .wordpress-org/screenshot-4.png
  .wordpress-org/screenshot-5.png
  .wordpress-org/screenshot-6.png
  README.md
Labels: Type: Documentation, Changelog: Changed
