Repository Parsely/wp-parsely, pull requests merged in 2022-12, with the labels that each got.

#1220 Content Helper: Fix tag param while requesting Parse.ly Analytics API
  build/content-helper.asset.php
  build/content-helper.js
  src/blocks/content-helper/content-helper-provider.ts
Labels: Changelog: Fixed

#1224 Integration Tests: Fix flaky tests related to Parse.ly metadata
  tests/Integration/Endpoints/RestMetadataTest.php
  tests/Integration/Metadata/SinglePostTest.php
  tests/Integration/UI/MetadataRendererTest.php
Labels: Type: Maintenance, Changelog: Skip

#1211 CONTRIBUTING.md: Improve for clarity
  CONTRIBUTING.md
Labels: Changelog: Skip

#1231 Move Parse.ly API base url to const for easier mocking during development
  src/Endpoints/class-analytics-posts-api-proxy.php
  src/blocks/shared/utils/constants.ts
  src/class-dashboard-link.php
  src/class-parsely.php
  tests/Integration/DashboardLinkTest.php
  tests/Integration/Endpoints/AnalyticsPostsProxyEndpointTest.php
  tests/Integration/UI/RowActionsTest.php
  tests/js/blocks/content-helper/structure.test.js
Labels: Changelog: Changed

#1229 Settings: Update radio options text to be more descriptive and easy to understand
  src/UI/class-settings-page.php
  tests/e2e/specs/front-end-metadata.spec.js
Labels: Changelog: Changed, Feature: wp-admin

#1230 Avoid extra WordPress_Cache instances while proxying the Parse.ly API
  wp-parsely.php
Labels: Changelog: Changed

#1093 Content Helper: Add "Current post details" panel
  build/content-helper.asset.php
  build/content-helper.css
  build/content-helper.js
  src/Endpoints/class-analytics-post-detail-api-proxy.php
  src/Endpoints/class-referrers-post-detail-api-proxy.php
  src/RemoteAPI/class-analytics-post-detail-proxy.php
  src/RemoteAPI/class-referrers-post-detail-proxy.php
  src/blocks/content-helper/content-helper.scss
  src/blocks/content-helper/content-helper.tsx
  src/blocks/content-helper/current-post-details/component.tsx
  src/blocks/content-helper/current-post-details/post-performance-data.ts
  src/blocks/content-helper/current-post-details/provider.ts
  src/blocks/content-helper/variables.scss
  tests/e2e/specs/blocks/content-helper/errors.spec.js
  tests/e2e/specs/blocks/content-helper/filters.spec.js
  tests/e2e/specs/blocks/content-helper/top-bar-icon.spec.js
  tests/e2e/utils.js
  wp-parsely.php
Labels: Changelog: Added, Feature: Content Helper

#1225 Content Helper: Fix blocked API requests caused by ad blockers
  build/content-helper.asset.php
  build/content-helper.css
  build/content-helper.js
  src/Endpoints/class-analytics-post-detail-api-proxy.php
  src/Endpoints/class-analytics-posts-api-proxy.php
  src/Endpoints/class-base-api-proxy.php
  src/blocks/content-helper/components/related-top-post-list.tsx
  src/blocks/content-helper/content-helper-provider.ts
  src/blocks/content-helper/content-helper.scss
  src/blocks/content-helper/current-post-details/component.tsx
  src/blocks/content-helper/current-post-details/provider.ts
  src/blocks/shared/components/error-hint.tsx
  src/blocks/shared/functions.scss
  src/blocks/shared/variables.scss
  tests/Integration/Endpoints/AnalyticsPostsProxyEndpointTest.php
  tests/js/blocks/content-helper/structure.test.js
Labels: Changelog: Fixed, Feature: Content Helper

#1237 Content Helper: Fix Parse.ly Posts API call for pages
  build/content-helper.asset.php
  build/content-helper.js
  src/blocks/content-helper/content-helper-provider.ts
Labels: Changelog: Changed, Feature: Content Helper

#1241 Settings Page: Rename "Track as Page" to "Track as Non-Post"
  README.md
  src/UI/class-settings-page.php
Labels: Changelog: Changed

#1245 Fix SonarCloud errors in develop branch
  src/blocks/content-helper/class-content-helper.php
  wp-parsely.php
Labels: Type: Maintenance, Changelog: Skip

#1249 Content Helper: Rename "Current Post Details" to "Performance Details"
  build/content-helper.asset.php
  build/content-helper.js
  src/blocks/content-helper/content-helper.tsx
  tests/e2e/specs/blocks/content-helper/top-bar-icon.spec.js
Labels: Changelog: Changed

#1232 Content Helper: Improve error handling
  .eslintrc
  build/blocks/recommendations/edit.asset.php
  build/blocks/recommendations/edit.js
  build/blocks/recommendations/view.asset.php
  build/blocks/recommendations/view.js
  build/content-helper.asset.php
  build/content-helper.js
  src/Endpoints/class-analytics-post-detail-api-proxy.php
  src/Endpoints/class-analytics-posts-api-proxy.php
  src/Endpoints/class-base-api-proxy.php
  src/Endpoints/class-referrers-post-detail-api-proxy.php
  src/Endpoints/class-related-api-proxy.php
  src/blocks/content-helper/components/related-top-post-list.tsx
  src/blocks/content-helper/content-helper-error.tsx
  src/blocks/content-helper/content-helper-provider.ts
  src/blocks/content-helper/current-post-details/component.tsx
  src/blocks/content-helper/current-post-details/provider.ts
  src/blocks/recommendations/components/parsely-recommendations.tsx
  src/blocks/shared/components/error-hint.tsx
  tests/Integration/ProxyEndpointTest.php
  tests/js/blocks/content-helper/structure.test.js
Labels: Type: Maintenance, Changelog: Changed, Feature: Content Helper

#1250 Settings page: Improve "Track as Non-Post" appearance
  build/admin-settings.asset.php
  build/admin-settings.css
  src/css/admin-settings.css
Labels: Changelog: Skip

#1240 Prepare README.md for the wp-parsely 3.6.0 release
  .wordpress-org/screenshot-1.png
  .wordpress-org/screenshot-2.png
  .wordpress-org/screenshot-3.png
  .wordpress-org/screenshot-4.png
  README.md
Labels: Type: Maintenance, Changelog: Skip

#1256 Update changelog for 3.6.0 release
  CHANGELOG.md
Labels: Changelog: Skip

#1257 Update CHANGELOG.md for 3.6.0 release
  CHANGELOG.md
Labels: Changelog: Skip

#1259 Revert composer autoloader PR
  .github/workflows/deploy.yml
  .github/workflows/e2e-tests.yml
  composer.json
  wp-parsely.php
Labels: Type: Bug, Changelog: Fixed

#1260 Update the wp-parsely version to 3.6.1
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
  tests/e2e/utils.js
  wp-parsely.php
Labels: Changelog: Skip

#1261 Release wp-parsely 3.6.1
  .github/workflows/deploy.yml
  .github/workflows/e2e-tests.yml
  CHANGELOG.md
  README.md
  composer.json
  package-lock.json
  package.json
  tests/e2e/utils.js
  wp-parsely.php
Labels: Changelog: Skip

#1239 Add TypeScript support to all remaining JavaScript files
  .eslintrc
  build/admin-settings.asset.php
  build/admin-settings.js
  build/blocks/recommendations/edit.asset.php
  build/blocks/recommendations/edit.js
  build/blocks/recommendations/view.asset.php
  build/blocks/recommendations/view.js
  build/content-helper.asset.php
  build/content-helper.js
  build/loader.asset.php
  build/loader.js
  build/recommended-widget.asset.php
  build/recommended-widget.js
  package-lock.json
  package.json
  src/@types/assets/svg.d.ts
  src/@types/assets/window.d.ts
  src/@types/assets/wp-e2e-test-utils.d.ts
  src/blocks/content-helper/components/related-top-post-list.tsx
  src/blocks/content-helper/content-helper-error.tsx
  src/blocks/content-helper/content-helper-provider.ts
  src/blocks/content-helper/current-post-details/component.tsx
  src/blocks/content-helper/current-post-details/provider.ts
  src/blocks/recommendations/actions.ts
  src/blocks/recommendations/components/parsely-recommendations-fetcher.tsx
  src/blocks/recommendations/constants.ts
  src/blocks/recommendations/recommendations-store.js
  src/blocks/recommendations/recommendations-store.tsx
  src/js/admin-settings.js
  src/js/admin-settings.ts
  src/js/lib/loader.ts
  src/js/lib/personalization.ts
  src/js/lib/uuid-profile-call.ts
  src/js/widgets/recommended.ts
  tests/e2e/specs/activation-flow.spec.ts
  tests/e2e/specs/blocks/content-helper/errors.spec.ts
  tests/e2e/specs/blocks/content-helper/filters.spec.ts
  tests/e2e/specs/blocks/content-helper/top-bar-icon.spec.ts
  tests/e2e/specs/blocks/recommendations/errors.spec.ts
  tests/e2e/specs/blocks/recommendations/settings.spec.ts
  tests/e2e/specs/browse-logo-button.spec.ts
  tests/e2e/specs/front-end-metadata.spec.ts
  tests/e2e/specs/front-end-tracker.spec.ts
  tests/e2e/specs/plugin-action-link.spec.ts
  tests/e2e/specs/recommended-widget.spec.ts
  tests/e2e/specs/settings-track-post-types-as.spec.ts
  tests/e2e/utils.ts
  tests/js/blocks/content-helper/structure.test.tsx
  tests/js/blocks/recommendations/structure.test.tsx
  tests/js/lib/personalization.test.ts
  tsconfig.json
  webpack.config.js
Labels: Type: Refactoring, Changelog: Added

#1252 Fix PHPStan Errors
  composer.json
  phpstan.neon
  src/Endpoints/class-analytics-post-detail-api-proxy.php
  src/Endpoints/class-analytics-posts-api-proxy.php
  src/Endpoints/class-base-api-proxy.php
  src/Endpoints/class-graphql-metadata.php
  src/Endpoints/class-referrers-post-detail-api-proxy.php
  src/Endpoints/class-related-api-proxy.php
  src/Endpoints/class-rest-metadata.php
  src/Integrations/class-amp.php
  src/Integrations/class-facebook-instant-articles.php
  src/Integrations/class-integrations.php
  src/Metadata/class-author-archive-builder.php
  src/Metadata/class-category-builder.php
  src/Metadata/class-date-builder.php
  src/Metadata/class-page-for-posts-builder.php
  src/Metadata/class-post-builder.php
  src/Metadata/class-tag-builder.php
  src/RemoteAPI/class-cached-proxy.php
  src/RemoteAPI/class-wordpress-cache.php
  src/RemoteAPI/interface-proxy.php
  src/UI/class-admin-bar.php
  src/UI/class-metadata-renderer.php
  src/UI/class-network-admin-sites-list.php
  src/UI/class-plugins-actions.php
  src/UI/class-recommended-widget.php
  src/UI/class-settings-page.php
  src/UI/class-site-health.php
  src/Utils/utils.php
  src/blocks/recommendations/class-recommendations-block.php
  src/class-metadata.php
  src/class-parsely.php
  src/class-scripts.php
  tests/Integration/ScriptsTest.php
  tests/Integration/TestCase.php
  tests/Integration/UI/SettingsPageTest.php
  views/repeated-metas.php
  wp-parsely.php
Labels: Type: Refactoring, Changelog: Fixed

#1246 Fix SonarCloud warnings
  build/blocks/recommendations/edit.asset.php
  build/blocks/recommendations/edit.js
  build/blocks/recommendations/view.asset.php
  build/blocks/recommendations/view.js
  src/Endpoints/class-analytics-post-detail-api-proxy.php
  src/Endpoints/class-analytics-posts-api-proxy.php
  src/Endpoints/class-referrers-post-detail-api-proxy.php
  src/Endpoints/class-related-api-proxy.php
  src/Metadata/class-post-builder.php
  src/RemoteAPI/class-base-proxy.php
  src/UI/class-metadata-renderer.php
  src/UI/class-recommended-widget.php
  src/UI/class-settings-page.php
  src/blocks/content-helper/class-content-helper.php
  src/blocks/recommendations/components/parsely-recommendations-inspector-controls.tsx
  src/blocks/recommendations/components/parsely-recommendations-list.tsx
  src/blocks/recommendations/view.tsx
  src/class-parsely.php
  src/class-scripts.php
  tests/Integration/Endpoints/AnalyticsPostsProxyEndpointTest.php
  tests/Integration/Endpoints/RelatedProxyEndpointTest.php
  tests/Integration/Integrations/IntegrationsTest.php
  tests/Integration/Metadata/HomePageTest.php
  tests/Integration/Metadata/NonPostTestCase.php
  tests/Integration/Metadata/SinglePostTest.php
  tests/Integration/ScriptsTest.php
  tests/Integration/TestCase.php
  tests/Integration/UI/SettingsPageTest.php
  tests/Unit/Integrations/IntegrationsTest.php
Labels: Type: Refactoring, Changelog: Fixed

#1244 Rename API Key to Site ID to improve consistency
  build/loader.asset.php
  build/loader.js
  src/@types/assets/window.d.ts
  src/Endpoints/class-analytics-post-detail-api-proxy.php
  src/Endpoints/class-analytics-posts-api-proxy.php
  src/Endpoints/class-base-api-proxy.php
  src/Endpoints/class-graphql-metadata.php
  src/Endpoints/class-rest-metadata.php
  src/Integrations/class-amp.php
  src/Integrations/class-facebook-instant-articles.php
  src/Integrations/class-google-web-stories.php
  src/RemoteAPI/class-base-proxy.php
  src/UI/class-admin-bar.php
  src/UI/class-admin-warning.php
  src/UI/class-metadata-renderer.php
  src/UI/class-network-admin-sites-list.php
  src/UI/class-recommended-widget.php
  src/UI/class-row-actions.php
  src/UI/class-settings-page.php
  src/UI/class-site-health.php
  src/class-dashboard-link.php
  src/class-parsely.php
  src/class-scripts.php
  src/js/lib/uuid-profile-call.ts
  tests/Integration/DashboardLinkTest.php
  tests/Integration/Endpoints/AnalyticsPostsProxyEndpointTest.php
  tests/Integration/Endpoints/GraphQLMetadataTest.php
  tests/Integration/Endpoints/RelatedProxyEndpointTest.php
  tests/Integration/Endpoints/RestMetadataTest.php
  tests/Integration/Integrations/AmpTest.php
  tests/Integration/Integrations/FacebookInstantArticlesTest.php
  tests/Integration/OtherTest.php
  tests/Integration/ProxyEndpointTest.php
  tests/Integration/RemoteAPITest.php
  tests/Integration/ScriptsTest.php
  tests/Integration/UI/AdminWarningTest.php
  tests/Integration/UI/MetadataRendererTest.php
  tests/Integration/UI/NetworkAdminSitesListTest.php
  tests/Integration/UI/RowActionsTest.php
  tests/Integration/UI/SiteHealthTest.php
  tests/Unit/SettingsPage/ValidationsTest.php
  tests/e2e/specs/activation-flow.spec.ts
  tests/e2e/specs/blocks/recommendations/errors.spec.ts
  tests/e2e/specs/front-end-tracker.spec.ts
  tests/e2e/specs/recommended-widget.spec.ts
Labels: Type: Refactoring, Changelog: Changed
