Repository Parsely/wp-parsely, pull requests merged in 2023-08, with the labels that each got.

#1753 README.md: Update "Tested up to" to 6.3
  README.md
Labels: Status: Do not merge

#1784 Prevent always saving settings on Parsely->run()
  src/class-parsely.php
Labels: Changelog: Fixed

#1789 Analytics_Posts_API: Increase request timeout
  src/RemoteAPI/class-analytics-posts-api.php
  src/RemoteAPI/class-remote-api-base.php
  tests/Integration/Endpoints/AnalyticsPostsProxyEndpointTest.php
  tests/Integration/Endpoints/ReferrersPostDetailProxyEndpointTest.php
  tests/Integration/Endpoints/RelatedProxyEndpointTest.php
  tests/Integration/Endpoints/StatsPostDetailProxyEndpointTest.php
Labels: Changelog: Changed

#1797 Content Helper: Fix critical error due to direct views being null
  src/Endpoints/class-referrers-post-detail-api-proxy.php
Labels: Type: Bug, Changelog: Fixed, Feature: Content Helper

#1803 Improve argument of wp_parsely_credentials from bool to array
  src/class-parsely.php
Labels: Changelog: Changed

#1805 Content Helper: Show hint when HTTP errors are encountered
  build/content-helper/dashboard-widget.asset.php
  build/content-helper/dashboard-widget.js
  build/content-helper/editor-sidebar.asset.php
  build/content-helper/editor-sidebar.js
  src/content-helper/common/content-helper-error.tsx
  tests/js/content-helper/content-helper-error.test.ts
Labels: Changelog: Added
