Repository Parsely/wp-parsely, pull requests merged in 2023-02, with the labels that each got.

#1342 Fix PHP Notice on Settings page: "Undefined index: title"
  src/UI/class-settings-page.php
Labels: Changelog: Fixed

#1346 Add edit post icon and make linking behavior consistent across features
  build/content-helper.asset.php
  build/content-helper.css
  build/content-helper.js
  build/content-helper/dashboard-widget.asset.php
  build/content-helper/dashboard-widget.css
  build/content-helper/dashboard-widget.js
  src/blocks/content-helper/content-helper.scss
  src/blocks/content-helper/icons/edit-icon.tsx
  src/blocks/content-helper/icons/open-link-icon.tsx
  src/blocks/content-helper/related-top-posts/component-list-item.tsx
  src/blocks/content-helper/related-top-posts/model.ts
  src/blocks/shared/utils/post.ts
  src/content-helper/dashboard-widget/dashboard-widget.scss
  src/content-helper/dashboard-widget/top-posts/component-list-item.tsx
  tests/js/blocks/content-helper/structure.test.tsx
Labels: Changelog: Added, Feature: Content Helper

#1362 Fix PHP 8 incompatibilities
  src/Endpoints/class-analytics-post-detail-api-proxy.php
  src/Endpoints/class-referrers-post-detail-api-proxy.php
  tests/Integration/Endpoints/AnalyticsPostsProxyEndpointTest.php
  tests/Integration/Endpoints/ReferrersPostDetailProxyEndpointTest.php
  tests/Integration/Endpoints/RelatedProxyEndpointTest.php
  tests/Integration/Endpoints/StatsPostDetailProxyEndpointTest.php
  tests/Integration/ProxyEndpointTest.php
Labels: Type: Bug, Component: PHP, Changelog: Fixed

#1369 Add SECURITY.md
  SECURITY.md
Labels: Changelog: Skip

#1374 Content Helper: Fix top referrers percentage displaying as "NaN"
  src/Endpoints/class-referrers-post-detail-api-proxy.php
  src/Utils/utils.php
  tests/Integration/Endpoints/ReferrersPostDetailProxyEndpointTest.php
  tests/Integration/ProxyEndpointTest.php
Labels: Type: Bug, Changelog: Fixed, Feature: Content Helper

#1379 Fix Undefined warnings on Performance Details panel
  src/Endpoints/class-referrers-post-detail-api-proxy.php
Labels: Changelog: Fixed

#1378 Fix Undefined warnings on Performance Details panel
  src/Endpoints/class-referrers-post-detail-api-proxy.php
Labels: Changelog: Fixed

#1366 Increase PHPStan coverage by including tests in analysing
  composer.json
  phpstan.neon
  src/Integrations/class-amp.php
  src/Integrations/class-facebook-instant-articles.php
  src/Metadata/class-post-builder.php
  src/UI/class-recommended-widget.php
  src/UI/class-settings-page.php
  src/UI/class-site-health.php
  src/class-metadata.php
  src/class-parsely.php
  tests/Integration/DashboardLinkTest.php
  tests/Integration/Endpoints/RelatedProxyEndpointTest.php
  tests/Integration/Endpoints/RestMetadataTest.php
  tests/Integration/Endpoints/StatsPostDetailProxyEndpointTest.php
  tests/Integration/Integrations/AmpTest.php
  tests/Integration/Integrations/FacebookInstantArticlesTest.php
  tests/Integration/Integrations/GoogleWebStoriesTest.php
  tests/Integration/Integrations/IntegrationsTest.php
  tests/Integration/Metadata/AuthorArchiveTest.php
  tests/Integration/Metadata/BlogArchiveTest.php
  tests/Integration/Metadata/CustomPostTypeArchiveTest.php
  tests/Integration/Metadata/CustomTaxonomyTermArchiveTest.php
  tests/Integration/Metadata/DateArchiveTest.php
  tests/Integration/Metadata/GetCurrentUrlTest.php
  tests/Integration/Metadata/HomePageTest.php
  tests/Integration/Metadata/NonPostTestCase.php
  tests/Integration/Metadata/SinglePageTest.php
  tests/Integration/Metadata/SinglePostTest.php
  tests/Integration/Metadata/TermArchiveTest.php
  tests/Integration/OtherTest.php
  tests/Integration/ProxyEndpointTest.php
  tests/Integration/RemoteAPI/AnalyticsPostsRemoteAPITest.php
  tests/Integration/RemoteAPI/RelatedRemoteAPITest.php
  tests/Integration/RemoteAPITest.php
  tests/Integration/ScriptsTest.php
  tests/Integration/TestCase.php
  tests/Integration/UI/AdminColumnsParselyStatsTest.php
  tests/Integration/UI/AdminWarningTest.php
  tests/Integration/UI/MetadataRendererTest.php
  tests/Integration/UI/NetworkAdminSitesListTest.php
  tests/Integration/UI/RowActionsTest.php
  tests/Integration/UI/SettingsPageTest.php
  tests/Integration/UI/SiteHealthTest.php
  tests/Integration/bootstrap.php
  tests/Unit/Integrations/IntegrationsTest.php
  tests/trait-tests-reflection.php
Labels: Type: Maintenance, Component: PHP, Changelog: Skip

#1381 Fix referral distribution in Performance Details panel
  src/RemoteAPI/class-remote-api-base.php
  src/RemoteAPI/class-remote-api-cache.php
  tests/Integration/RemoteAPITest.php
Labels: Changelog: Fixed

#1382 Fix referral distribution in Performance Details panel v3.6
  CHANGELOG.md
  src/RemoteAPI/class-base-proxy.php
  src/RemoteAPI/class-cached-proxy.php
  tests/Integration/RemoteAPITest.php
Labels: Changelog: Skip

#1364 Release wp-parsely 3.6.2
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
  src/Endpoints/class-analytics-post-detail-api-proxy.php
  src/Endpoints/class-analytics-posts-api-proxy.php
  src/Endpoints/class-base-api-proxy.php
  src/Endpoints/class-referrers-post-detail-api-proxy.php
  src/Endpoints/class-related-api-proxy.php
  src/RemoteAPI/class-base-proxy.php
  src/RemoteAPI/class-cached-proxy.php
  tests/Integration/Endpoints/AnalyticsPostsProxyEndpointTest.php
  tests/Integration/RemoteAPITest.php
  tests/e2e/utils.js
  wp-parsely.php
Labels: Changelog: Skip

#1385 Merge trunk into develop after wp-parsely 3.6.2 release
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
  src/Endpoints/class-analytics-post-detail-api-proxy.php
  src/Endpoints/class-analytics-posts-api-proxy.php
  src/Endpoints/class-base-api-proxy.php
  src/Endpoints/class-referrers-post-detail-api-proxy.php
  src/Endpoints/class-related-api-proxy.php
  src/RemoteAPI/class-remote-api-cache.php
  src/class-dashboard-link.php
  tests/Integration/Endpoints/AnalyticsPostsProxyEndpointTest.php
  tests/Integration/Endpoints/ReferrersPostDetailProxyEndpointTest.php
  tests/Integration/Endpoints/StatsPostDetailProxyEndpointTest.php
  tests/e2e/utils.ts
  wp-parsely.php
Labels: Changelog: Skip

#1387 Prepare README.md for the wp-parsely 3.7.0 release
  .wordpress-org/screenshot-4.png
  .wordpress-org/screenshot-5.png
  .wordpress-org/screenshot-6.png
  .wordpress-org/screenshot-7.png
  .wordpress-org/screenshot-8.png
  README.md
Labels: Changelog: Skip

#1380 Content Helper: Improve naming
  build/content-helper.asset.php
  build/content-helper.js
  src/blocks/content-helper/class-content-helper.php
  src/blocks/content-helper/content-helper.tsx
  src/blocks/content-helper/related-top-posts/provider.ts
  src/content-helper/dashboard-widget/class-dashboard-widget.php
  src/content-helper/dashboard-widget/provider.ts
  tests/Integration/Blocks/ContentHelperTest.php
  tests/e2e/specs/blocks/content-helper/errors.spec.ts
  tests/e2e/specs/blocks/content-helper/filters.spec.ts
  tests/e2e/specs/blocks/content-helper/top-bar-icon.spec.ts
  tests/e2e/utils.ts
  tests/js/blocks/content-helper/structure.test.tsx
  wp-parsely.php
Labels: Changelog: Skip, Feature: Content Helper, Feature: wp-admin

#1401 Upgrade minimum PHP version to 7.2
  .github/workflows/integration-tests.yml
  .github/workflows/unit-tests.yml
  composer.json
  wp-parsely.php
Labels: Changelog: Changed

#1270 Rector: Add rector
  composer.json
  rector.php
  src/Endpoints/class-referrers-post-detail-api-proxy.php
  src/Metadata/class-post-builder.php
  src/UI/class-network-admin-sites-list.php
  src/blocks/recommendations/class-recommendations-block.php
  src/class-parsely.php
  tests/Integration/Integrations/FacebookInstantArticlesTest.php
  tests/Integration/Metadata/AuthorArchiveTest.php
  tests/Integration/Metadata/BlogArchiveTest.php
  tests/Integration/Metadata/CustomPostTypeArchiveTest.php
  tests/Integration/Metadata/CustomTaxonomyTermArchiveTest.php
  tests/Integration/Metadata/HomePageTest.php
  tests/Integration/Metadata/SinglePageTest.php
  tests/Integration/Metadata/TermArchiveTest.php
  tests/Integration/OtherTest.php
  tests/Integration/ScriptsTest.php
  tests/Integration/UI/AdminColumnsParselyStatsTest.php
  tests/Integration/UI/SiteHealthTest.php
Labels: Type: Maintenance

#1407 Refactor permission checks to hide Parse.ly widget and stats column based on user capabilities
  src/Endpoints/class-analytics-post-detail-api-proxy.php
  src/Endpoints/class-analytics-posts-api-proxy.php
  src/Endpoints/class-base-api-proxy.php
  src/Endpoints/class-referrers-post-detail-api-proxy.php
  src/Endpoints/class-related-api-proxy.php
  src/RemoteAPI/class-analytics-post-detail-api.php
  src/RemoteAPI/class-analytics-posts-api.php
  src/RemoteAPI/class-referrers-post-detail-api.php
  src/RemoteAPI/class-related-api.php
  src/RemoteAPI/class-remote-api-base.php
  src/RemoteAPI/class-remote-api-cache.php
  src/RemoteAPI/interface-remote-api.php
  src/UI/class-admin-columns-parsely-stats.php
  src/content-helper/dashboard-widget/class-dashboard-widget.php
  tests/Integration/TestCase.php
  tests/Integration/UI/AdminColumnsParselyStatsTest.php
Labels: Changelog: Changed

#1269 Add type coverage
  composer.json
  phpstan.neon
Labels: Type: Maintenance, Changelog: Added

#1416 Add shell script for updating the wp-parsely version number
  bin/uvn.sh
Labels: Type: Maintenance, Changelog: Skip

#1417 Add filters to configure user capability on remote APIs
  src/Endpoints/class-base-api-proxy.php
  src/RemoteAPI/class-analytics-post-detail-api.php
  src/RemoteAPI/class-analytics-posts-api.php
  src/RemoteAPI/class-referrers-post-detail-api.php
  src/RemoteAPI/class-related-api.php
  src/RemoteAPI/class-remote-api-base.php
  src/Utils/utils.php
  tests/Integration/Endpoints/AnalyticsPostsProxyEndpointTest.php
  tests/Integration/Endpoints/ReferrersPostDetailProxyEndpointTest.php
  tests/Integration/Endpoints/StatsPostDetailProxyEndpointTest.php
  tests/Integration/RemoteAPI/AnalyticsPostsRemoteAPITest.php
  tests/Integration/RemoteAPI/RelatedRemoteAPITest.php
  tests/Integration/TestCase.php
Labels: Changelog: Added

#1339 Move screen options of Parse.ly settings in their dedicated tabs
  .github/workflows/release-drafter.yml
  .wordpress-org/screenshot-1.png
  .wordpress-org/screenshot-2.png
  .wordpress-org/screenshot-3.png
  README.md
  bin/uvn.sh
  build/admin-settings.asset.php
  build/admin-settings.js
  package-lock.json
  package.json
  src/Endpoints/class-analytics-post-detail-api-proxy.php
  src/Endpoints/class-analytics-posts-api-proxy.php
  src/Endpoints/class-base-api-proxy.php
  src/Endpoints/class-referrers-post-detail-api-proxy.php
  src/Endpoints/class-related-api-proxy.php
  src/RemoteAPI/class-analytics-post-detail-api.php
  src/RemoteAPI/class-analytics-posts-api.php
  src/RemoteAPI/class-referrers-post-detail-api.php
  src/RemoteAPI/class-related-api.php
  src/RemoteAPI/class-remote-api-base.php
  src/RemoteAPI/class-remote-api-cache.php
  src/RemoteAPI/interface-remote-api.php
  src/UI/class-admin-columns-parsely-stats.php
  src/UI/class-settings-page.php
  src/Utils/utils.php
  src/class-dashboard-link.php
  src/content-helper/dashboard-widget/class-dashboard-widget.php
  src/js/admin-settings.ts
  tests/Integration/Endpoints/AnalyticsPostsProxyEndpointTest.php
  tests/Integration/Endpoints/ReferrersPostDetailProxyEndpointTest.php
  tests/Integration/Endpoints/StatsPostDetailProxyEndpointTest.php
  tests/Integration/RemoteAPI/AnalyticsPostsRemoteAPITest.php
  tests/Integration/RemoteAPI/RelatedRemoteAPITest.php
  tests/Integration/TestCase.php
  tests/Integration/UI/AdminColumnsParselyStatsTest.php
  tests/Integration/UI/SettingsPageTest.php
  tests/e2e/specs/activation-flow.spec.ts
  tests/e2e/specs/front-end-metadata.spec.ts
  tests/e2e/specs/settings-track-post-types-as.spec.ts
  tests/e2e/utils.ts
  views/parsely-settings.php
  wp-parsely.php
Labels: Changelog: Changed

#1420 Update version numbers and changelog for 3.7.0 release
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
  tests/e2e/utils.ts
  wp-parsely.php
Labels: Changelog: Skip

#1423 Hide Parse.ly Stats column if API Secret is not available
  src/UI/class-admin-columns-parsely-stats.php
  src/UI/class-metadata-renderer.php
  src/UI/class-settings-page.php
  tests/Integration/UI/AdminColumnsParselyStatsTest.php
Labels: Changelog: Fixed

#1424 Fix Recommended Widget fatal error
  src/UI/class-recommended-widget.php
Labels: Type: Bug, Changelog: Fixed

#1418 Update secret field types on settings page from text to password
  phpstan.neon
  src/UI/class-metadata-renderer.php
  src/UI/class-settings-page.php
Labels: Changelog: Changed
