Repository Parsely/wp-parsely, pull requests merged in 2023-01, with the labels that each got.

#1272 Improve Remote APIs naming
  build/loader.asset.php
  build/loader.js
  src/Endpoints/class-base-api-proxy.php
  src/RemoteAPI/class-analytics-post-detail-api.php
  src/RemoteAPI/class-analytics-post-detail-proxy.php
  src/RemoteAPI/class-analytics-posts-api.php
  src/RemoteAPI/class-analytics-posts-proxy.php
  src/RemoteAPI/class-referrers-post-detail-api.php
  src/RemoteAPI/class-referrers-post-detail-proxy.php
  src/RemoteAPI/class-related-api.php
  src/RemoteAPI/class-related-proxy.php
  src/RemoteAPI/class-remote-api-base.php
  src/RemoteAPI/class-remote-api-cache.php
  src/RemoteAPI/interface-remote-api.php
  src/UI/class-recommended-widget.php
  src/blocks/shared/utils/constants.ts
  src/class-parsely.php
  src/js/lib/uuid-profile-call.ts
  tests/Integration/Endpoints/AnalyticsPostsProxyEndpointTest.php
  tests/Integration/Endpoints/RelatedProxyEndpointTest.php
  tests/Integration/RemoteAPI/AnalyticsPostsRemoteAPITest.php
  tests/Integration/RemoteAPI/RelatedRemoteAPITest.php
  tests/Integration/RemoteAPITest.php
  wp-parsely.php
Labels: Changelog: Changed

#1285 GitHub templates: Add public repo notice
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
Labels: Changelog: Skip

#1287 Centralize dashboard URL generation in a single function
  build/content-helper.asset.php
  build/content-helper.js
  src/Endpoints/class-analytics-post-detail-api-proxy.php
  src/Endpoints/class-analytics-posts-api-proxy.php
  src/blocks/content-helper/components/related-top-post-list-item.tsx
  src/blocks/content-helper/current-post-details/component.tsx
  src/blocks/content-helper/current-post-details/post-performance-data.ts
  src/blocks/content-helper/models/related-top-post-data.ts
  src/class-dashboard-link.php
  src/class-parsely.php
  tests/Integration/Endpoints/AnalyticsPostsProxyEndpointTest.php
  tests/js/blocks/content-helper/structure.test.tsx
Labels: Changelog: Changed

#1286 CODEOWNERS: Ignore package.json and package-lock.json
  .github/CODEOWNERS
Labels: Changelog: Skip

#1288 Refactor Content Helper for better structure
  build/content-helper.asset.php
  build/content-helper.css
  build/content-helper.js
  src/blocks/content-helper/content-helper.scss
  src/blocks/content-helper/content-helper.tsx
  src/blocks/content-helper/performance-details/component.tsx
  src/blocks/content-helper/performance-details/model.ts
  src/blocks/content-helper/performance-details/provider.ts
  src/blocks/content-helper/related-top-posts/component-list-item.tsx
  src/blocks/content-helper/related-top-posts/component-list.tsx
  src/blocks/content-helper/related-top-posts/model.ts
  src/blocks/content-helper/related-top-posts/provider.ts
  src/blocks/content-helper/variables.scss
  src/blocks/shared/variables.scss
  tests/js/blocks/content-helper/structure.test.tsx
Labels: Changelog: Changed

#1302 UI: Fix typo in Disable JavaScript option
  src/UI/class-settings-page.php
Labels: Type: Bug, Changelog: Changed

#1303 UI: Fix grammar in Content Helper error
  build/content-helper.asset.php
  build/content-helper.js
  src/blocks/content-helper/content-helper-error.tsx
  tests/js/blocks/content-helper/structure.test.tsx
Labels: Type: Bug, Changelog: Changed

#1304 UI: Minor wording tweak for Content Helper error
  build/content-helper.asset.php
  build/content-helper.js
  src/blocks/content-helper/performance-details/provider.ts
Labels: Type: Maintenance, Changelog: Changed

#1326 Add PHPStan analysing check in pre-commit hook
  .husky/pre-commit
  src/Integrations/class-integrations.php
  src/UI/class-admin-bar.php
  src/UI/class-settings-page.php
  src/Utils/utils.php
Labels: Changelog: Added

#1327 🐛 FIX: showing Parse.ly Stats on multiple columns
  src/UI/class-admin-columns-parsely-stats.php
  tests/Integration/UI/AdminColumnsParselyStatsTest.php
Labels: Changelog: Skip

#1331 Improves Parse.ly Stats on post list screen
  src/UI/class-admin-columns-parsely-stats.php
  tests/Integration/UI/AdminColumnsParselyStatsTest.php
Labels: Changelog: Skip

#1305 Add WordPress Dashboard Widget
  build/content-helper.asset.php
  build/content-helper.css
  build/content-helper.js
  build/content-helper/dashboard-widget.asset.php
  build/content-helper/dashboard-widget.css
  build/content-helper/dashboard-widget.js
  src/Endpoints/class-analytics-posts-api-proxy.php
  src/blocks/content-helper/performance-details/component.tsx
  src/blocks/content-helper/performance-details/provider.ts
  src/blocks/shared/functions.ts
  src/blocks/shared/utils/date.ts
  src/content-helper/dashboard-widget/class-dashboard-widget.php
  src/content-helper/dashboard-widget/dashboard-widget.scss
  src/content-helper/dashboard-widget/dashboard-widget.tsx
  src/content-helper/dashboard-widget/provider.ts
  src/content-helper/dashboard-widget/top-posts/component-list-item.tsx
  src/content-helper/dashboard-widget/top-posts/component-list.tsx
  src/content-helper/dashboard-widget/top-posts/model.ts
  src/css/shared/variables.scss
  tests/Integration/Endpoints/AnalyticsPostsProxyEndpointTest.php
  webpack.config.js
  wp-parsely.php
Labels: Changelog: Added, Feature: Content Helper

#1336 Content Helper: Make error hint display for all Forbidden (403) errors
  build/content-helper.asset.php
  build/content-helper.js
  build/content-helper/dashboard-widget.asset.php
  build/content-helper/dashboard-widget.js
  src/blocks/content-helper/content-helper-error.tsx
Labels: Changelog: Fixed
