Repository Parsely/wp-parsely, pull requests merged in 2023-09, with the labels that each got.

#1847 Upgrade to React 18 and fix depedency issues
  build/blocks/recommendations/edit.asset.php
  build/blocks/recommendations/edit.js
  build/blocks/recommendations/view.asset.php
  build/blocks/recommendations/view.js
  build/content-helper/dashboard-widget.asset.php
  build/content-helper/dashboard-widget.js
  build/content-helper/editor-sidebar.asset.php
  build/content-helper/editor-sidebar.js
  build/recommended-widget.asset.php
  build/recommended-widget.js
  jest-unit.config.js
  package-lock.json
  package.json
  src/blocks/recommendations/components/parsely-recommendations-inspector-controls.tsx
  src/content-helper/common/content-helper-error-message.tsx
  src/content-helper/common/verify-credentials.tsx
  tests/e2e/specs/plugin-action-link.spec.ts
Labels: Type: Maintenance, Changelog: Changed

#1848 Run our plugin code through Rector
  rector.php
  src/class-parsely.php
Labels: Type: Maintenance

#1849 Update Recommendations Block API version to 3
  build/blocks/recommendations/block.json
  src/blocks/recommendations/block.json
Labels: Type: Maintenance, Feature: Recommendations Block

#1858 PCH Top Related Posts: Respect tag case sensitivity
  build/content-helper/editor-sidebar.asset.php
  build/content-helper/editor-sidebar.js
  src/content-helper/editor-sidebar/related-top-posts/provider.ts
Labels: Changelog: Fixed

#1859 Update Site ID column in Network Admin List to show — instead of text
  src/UI/class-network-admin-sites-list.php
  tests/Integration/UI/NetworkAdminSitesListTest.php
Labels: Changelog: Changed

#1860 Remove Intl dependency from utils.php
  src/Utils/utils.php
  src/content-helper/post-list-stats/class-post-list-stats.php
  tests/Integration/content-helper/ContentHelperPostListStatsTest.php
  tests/Unit/Utils/UtilsTest.php
Labels: Changelog: Fixed

#1876 Dashboard Widget: Add period and metric filters
  build/content-helper/dashboard-widget.asset.php
  build/content-helper/dashboard-widget.css
  build/content-helper/dashboard-widget.js
  src/content-helper/common/select.tsx
  src/content-helper/dashboard-widget/class-dashboard-widget.php
  src/content-helper/dashboard-widget/components/top-posts-list-item.tsx
  src/content-helper/dashboard-widget/components/top-posts.tsx
  src/content-helper/dashboard-widget/dashboard-widget.scss
  src/content-helper/dashboard-widget/dashboard-widget.tsx
  src/content-helper/dashboard-widget/model.ts
  src/content-helper/dashboard-widget/provider.ts
  src/content-helper/dashboard-widget/top-posts/component-list.tsx
Labels: Changelog: Added, Feature: Content Helper

#1893 Fix Integration tests on PHP 8.2 and 8.3
  tests/Integration/ScriptsTest.php
Labels: Type: Maintenance, Component: PHP, php

#1894 Remove "boost" field from Recommendations Block and Widget
  build/blocks/recommendations/block.json
  build/blocks/recommendations/edit.asset.php
  build/blocks/recommendations/edit.js
  build/blocks/recommendations/view.asset.php
  build/blocks/recommendations/view.js
  src/UI/class-recommended-widget.php
  src/blocks/recommendations/block.json
  src/blocks/recommendations/components/parsely-recommendations-fetcher.tsx
  src/blocks/recommendations/components/parsely-recommendations-inspector-controls.tsx
  src/blocks/recommendations/components/parsely-recommendations.tsx
  src/blocks/recommendations/models/RecommendationsAttributes.ts
  tests/Integration/RemoteAPI/RelatedRemoteAPITest.php
  tests/js/blocks/recommendations/structure.test.tsx
Labels: Feature: Recommendations Block, Changelog: Removed
