Repository Parsely/wp-parsely, pull requests merged in 2023-03, with the labels that each got.

#1431 Make additional PHP 7.2 adjustments
  CONTRIBUTING.md
  README.md
  tests/Integration/TestCase.php
  tests/Integration/UI/AdminColumnsParselyStatsTest.php
Labels: Changelog: Changed

#1436 Update the "Track Logged-in Users" option to off by default
  src/class-parsely.php
  tests/Integration/OtherTest.php
  tests/Integration/ScriptsTest.php
  tests/Integration/TestCase.php
  tests/e2e/specs/front-end-metadata.spec.ts
Labels: Changelog: Changed

#1443 Fix flaky test that verifies loader script
  phpstan.neon
  src/UI/class-admin-columns-parsely-stats.php
  src/UI/class-recommended-widget.php
  src/UI/class-settings-page.php
  src/Utils/utils.php
  src/blocks/content-helper/class-content-helper.php
  src/class-scripts.php
  src/content-helper/dashboard-widget/class-dashboard-widget.php
  tests/Integration/ScriptsTest.php
Labels: Changelog: Fixed

#1451 Add days info in header of Parsely Stats column
  src/UI/class-admin-columns-parsely-stats.php
  tests/Integration/UI/AdminColumnsParselyStatsTest.php
Labels: Changelog: Changed, Feature: Content Helper

#1454 Update Related Top Posts range to 7 days
  build/content-helper.asset.php
  build/content-helper.js
  build/content-helper/dashboard-widget.asset.php
  build/content-helper/dashboard-widget.js
  src/UI/class-admin-columns-parsely-stats.php
  src/blocks/content-helper/performance-details/provider.ts
  src/blocks/content-helper/related-top-posts/provider.ts
  src/blocks/shared/utils/api.ts
  src/content-helper/dashboard-widget/provider.ts
  tests/Integration/UI/AdminColumnsParselyStatsTest.php
  tests/e2e/specs/blocks/content-helper/filters.spec.ts
Labels: Changelog: Changed, Feature: Content Helper

#1467 Content Helper: Fix period range issue on Performance Details panel
  bin/release.php
  build/content-helper.asset.php
  build/content-helper.js
  build/content-helper/dashboard-widget.asset.php
  build/content-helper/dashboard-widget.js
  src/blocks/content-helper/performance-details/component.tsx
  src/blocks/content-helper/performance-details/model.ts
  src/blocks/content-helper/performance-details/provider.ts
  src/blocks/shared/utils/api.ts
Labels: Changelog: Fixed, Feature: Content Helper

#1477 Fix some fatal errors and warnings
  src/Endpoints/class-analytics-posts-api-proxy.php
  src/UI/class-admin-bar.php
  src/UI/class-recommended-widget.php
  src/Utils/utils.php
Labels: Changelog: Fixed

#1482 Fix fatal errors in Co-Authors plugin integration
  src/Metadata/class-author-archive-builder.php
  src/Utils/utils.php
Labels: Changelog: Fixed

#1484 Fix Content Helper breakages due to null pub_date in API
  build/content-helper.asset.php
  build/content-helper.js
  build/content-helper/dashboard-widget.asset.php
  build/content-helper/dashboard-widget.js
  src/Endpoints/class-analytics-posts-api-proxy.php
  src/blocks/content-helper/performance-details/component.tsx
  src/blocks/content-helper/related-top-posts/component-list-item.tsx
  src/blocks/content-helper/related-top-posts/component-list.tsx
  src/blocks/shared/utils/date.ts
  src/content-helper/dashboard-widget/top-posts/component-list.tsx
  tests/js/blocks/content-helper/structure.test.tsx
  tests/js/blocks/shared/utils/date.test.tsx
Labels: Changelog: Fixed

#1491 PCH Stats Column: Fix avg time display issues
  src/UI/class-admin-columns-parsely-stats.php
  tests/Integration/UI/AdminColumnsParselyStatsTest.php
Labels: Changelog: Fixed

#1493 Fix Admin Bar "Undefined Property" warning
  src/UI/class-admin-bar.php
Labels: Changelog: Fixed

#1492 Fix NumberFormatter constructor failures
  src/Utils/utils.php
Labels: Changelog: Fixed

#1494 Fix "Attempt to read property name on null" warning
  src/Metadata/class-post-builder.php
Labels: Changelog: Fixed

#1268 Add VSCode Workspace Settings
  .gitignore
  .husky/pre-commit
  .vscode/wp-parsely.code-workspace
  CONTRIBUTING.md
Labels: Changelog: Added
