Repository Parsely/wp-parsely, pull requests merged in 2023-12, with the labels that each got.

#2035 Include VIP Go environment in JS telemetry
  build/content-helper/dashboard-widget.asset.php
  build/content-helper/dashboard-widget.js
  build/content-helper/editor-sidebar.asset.php
  build/content-helper/editor-sidebar.js
  build/telemetry.asset.php
  build/telemetry.js
  src/js/telemetry/telemetry.ts
Labels: Component: JavaScript, Changelog: Fixed

#2043 Add telemetry to Related Top Posts filter and to Title Suggestions panel
  build/content-helper/editor-sidebar.asset.php
  build/content-helper/editor-sidebar.js
  src/content-helper/editor-sidebar/editor-sidebar.tsx
  src/content-helper/editor-sidebar/related-top-posts/component-list.tsx
  src/content-helper/editor-sidebar/title-suggestions/component-title-suggestion.tsx
  src/content-helper/editor-sidebar/title-suggestions/component.tsx
Labels: Component: JavaScript, Changelog: Added

#2051 Update Content Suggestions API base URL
  src/class-parsely.php
Labels: Feature: Content Helper

#2052 Initialize Parse.ly options with default values
  src/UI/class-settings-page.php
Labels: Component: PHP, Changelog: Fixed

#2069 .phpcs.xml.dist: Fix erroneous rule property name
  .phpcs.xml.dist
Labels: Type: Maintenance

#2068 VSCode Workspace Settings: Update deprecated value
  .vscode/wp-parsely.code-workspace
Labels: Type: Maintenance

#2062 Content Helper: Add Excerpt Generator feature
  build/admin-settings.asset.php
  build/admin-settings.css
  build/blocks/recommendations/edit.asset.php
  build/blocks/recommendations/edit.js
  build/content-helper/dashboard-widget.asset.php
  build/content-helper/dashboard-widget.css
  build/content-helper/editor-sidebar.asset.php
  build/content-helper/editor-sidebar.css
  build/content-helper/editor-sidebar.js
  build/content-helper/excerpt-generator.asset.php
  build/content-helper/excerpt-generator.css
  build/content-helper/excerpt-generator.js
  package-lock.json
  package.json
  phpstan.neon
  src/@types/assets/window.d.ts
  src/Endpoints/class-base-api-proxy.php
  src/Endpoints/content-suggestions/class-suggest-meta-description-api-proxy.php
  src/RemoteAPI/content-suggestions/class-content-suggestions-base-api.php
  src/RemoteAPI/content-suggestions/class-suggest-meta-description-api.php
  src/RemoteAPI/content-suggestions/class-write-title-api.php
  src/content-helper/common/components/beta-badge.tsx
  src/content-helper/common/css/common.scss
  src/content-helper/common/css/variables.scss
  src/content-helper/common/icons/leaf-icon.tsx
  src/content-helper/excerpt-generator/class-excerpt-generator.php
  src/content-helper/excerpt-generator/components/excerpt-panel.tsx
  src/content-helper/excerpt-generator/excerpt-generator.scss
  src/content-helper/excerpt-generator/excerpt-generator.tsx
  src/content-helper/excerpt-generator/provider.ts
  tests/Integration/RemoteAPI/content-suggestions/SuggestMetaDescriptionAPITest.php
  tests/Integration/RemoteAPI/content-suggestions/WriteTitleAPITest.php
  webpack.config.js
  wp-parsely.php
Labels: Changelog: Added

#2086 PCH Title Suggestions: Add tone and persona options
  build/admin-settings.asset.php
  build/admin-settings.css
  build/content-helper/dashboard-widget.asset.php
  build/content-helper/dashboard-widget.css
  build/content-helper/editor-sidebar.asset.php
  build/content-helper/editor-sidebar.css
  build/content-helper/editor-sidebar.js
  build/content-helper/excerpt-generator.asset.php
  build/content-helper/excerpt-generator.css
  build/content-helper/excerpt-generator.js
  src/@types/gutenberg/types.ts
  src/Endpoints/content-suggestions/class-write-title-api-proxy.php
  src/RemoteAPI/content-suggestions/class-write-title-api.php
  src/content-helper/common/components/beta-badge/component.tsx
  src/content-helper/common/components/beta-badge/index.ts
  src/content-helper/common/components/beta-badge/style.scss
  src/content-helper/common/components/persona-selector/component.tsx
  src/content-helper/common/components/persona-selector/index.ts
  src/content-helper/common/components/persona-selector/style.scss
  src/content-helper/common/components/tone-selector/component.tsx
  src/content-helper/common/components/tone-selector/index.ts
  src/content-helper/common/components/tone-selector/style.scss
  src/content-helper/common/css/common.scss
  src/content-helper/common/css/variables.scss
  src/content-helper/common/icons/person-icon.tsx
  src/content-helper/editor-sidebar/editor-sidebar.scss
  src/content-helper/editor-sidebar/editor-sidebar.tsx
  src/content-helper/editor-sidebar/title-suggestions/component-settings.tsx
  src/content-helper/editor-sidebar/title-suggestions/component-title-suggestion.tsx
  src/content-helper/editor-sidebar/title-suggestions/component.tsx
  src/content-helper/editor-sidebar/title-suggestions/provider.ts
  src/content-helper/editor-sidebar/title-suggestions/store.ts
  src/content-helper/excerpt-generator/components/excerpt-panel.tsx
Labels: Component: PHP, Component: JavaScript, Changelog: Added, Feature: Content Helper

#2089 PCH: Add telemetry to Excerpt Generator and tone and persona AI settings
  build/content-helper/editor-sidebar.asset.php
  build/content-helper/editor-sidebar.js
  build/content-helper/excerpt-generator.asset.php
  build/content-helper/excerpt-generator.js
  src/content-helper/common/components/persona-selector/component.tsx
  src/content-helper/common/components/tone-selector/component.tsx
  src/content-helper/editor-sidebar/title-suggestions/component-settings.tsx
  src/content-helper/excerpt-generator/components/excerpt-panel.tsx
Labels: Type: Enhancement, Component: JavaScript
