Repository Parsely/wp-parsely, pull requests merged in 2023-11, with the labels that each got.

#1965 Add types/wordpress__editor devDependency
  build/content-helper/editor-sidebar.asset.php
  build/content-helper/editor-sidebar.js
  package-lock.json
  package.json
  src/content-helper/editor-sidebar/performance-details/provider.ts
  src/content-helper/editor-sidebar/related-top-posts/provider.ts
Labels: Type: Maintenance

#1993 update-version.sh: Update some strings
  bin/update-version.sh
Labels: Type: Maintenance

#1991 README.md: Update "Tested up to" to 6.4
  README.md
Labels: Type: Maintenance

#1992 Update wp-parsely version number to 3.11.0
  README.md
  package-lock.json
  package.json
  tests/e2e/utils.ts
  wp-parsely.php
Labels: Type: Maintenance

#1997 Update plugin screenshots
  .wordpress-org/screenshot-4.png
  .wordpress-org/screenshot-6.png
  .wordpress-org/screenshot-7.png
  .wordpress-org/screenshot-8.png
  .wordpress-org/screenshot-9.png
  README.md
Labels: Type: Maintenance

#1995 Metadata: Add filter for custom taxonomies
  src/Metadata/class-post-builder.php
Labels: Changelog: Added

#1994 Update required WordPress version to 5.2
  README.md
Labels: Type: Maintenance, Changelog: Changed

#1976 Implement a base endpoint class
  src/Endpoints/class-base-endpoint.php
  src/RemoteAPI/class-analytics-post-detail-api.php
  src/RemoteAPI/class-analytics-posts-api.php
  src/RemoteAPI/class-base-endpoint-remote.php
  src/RemoteAPI/class-referrers-post-detail-api.php
  src/RemoteAPI/class-related-api.php
  src/RemoteAPI/class-remote-api-cache.php
  src/RemoteAPI/class-validate-api.php
  src/content-helper/post-list-stats/class-post-list-stats.php
  tests/Integration/ContentHelperFeatureTest.php
  tests/Integration/Endpoints/AnalyticsPostsProxyEndpointTest.php
  tests/Integration/Endpoints/ReferrersPostDetailProxyEndpointTest.php
  tests/Integration/Endpoints/RelatedProxyEndpointTest.php
  tests/Integration/Endpoints/StatsPostDetailProxyEndpointTest.php
  tests/Integration/RemoteAPI/AnalyticsPostsRemoteAPITest.php
  tests/Integration/RemoteAPI/RelatedRemoteAPITest.php
  tests/Integration/RemoteAPITest.php
  tests/Integration/content-helper/ContentHelperDashboardWidgetTest.php
  tests/Integration/content-helper/ContentHelperPostListStatsTest.php
  wp-parsely.php
Labels: Type: Maintenance, Type: Refactoring, Changelog: Changed

#1986 PCH Related Top Posts: Add filter values drop-down
  build/content-helper/dashboard-widget.asset.php
  build/content-helper/dashboard-widget.js
  build/content-helper/editor-sidebar.asset.php
  build/content-helper/editor-sidebar.js
  build/loader.asset.php
  build/loader.js
  package-lock.json
  package.json
  src/Metadata/class-post-builder.php
  src/content-helper/common/utils/constants.ts
  src/content-helper/editor-sidebar/editor-sidebar.tsx
  src/content-helper/editor-sidebar/related-top-posts/component-filter-selection-controls.tsx
  src/content-helper/editor-sidebar/related-top-posts/component-list.tsx
  src/content-helper/editor-sidebar/related-top-posts/provider.ts
  tests/e2e/specs/content-helper/top-bar-icon.spec.ts
  tests/js/content-helper/structure.test.tsx
Labels: Changelog: Added, Feature: Content Helper

#2001 Initialize Parse.ly option before registering the setting
  src/UI/class-settings-page.php
Labels: Changelog: Fixed

#2009 Fix PHPStan errors in integration tests
  tests/Integration/TestCase.php
  tests/Integration/UI/NetworkAdminSitesListTest.php
Labels: Type: Maintenance

#1967 Content Helper Sidebar: Add Title Suggestions feature
  build/admin-settings.asset.php
  build/admin-settings.css
  build/content-helper/dashboard-widget.asset.php
  build/content-helper/dashboard-widget.css
  build/content-helper/dashboard-widget.js
  build/content-helper/editor-sidebar.asset.php
  build/content-helper/editor-sidebar.css
  build/content-helper/editor-sidebar.js
  package-lock.json
  package.json
  phpstan.neon
  src/Endpoints/content-suggestions/class-write-title-api-proxy.php
  src/RemoteAPI/class-analytics-post-detail-api.php
  src/RemoteAPI/class-analytics-posts-api.php
  src/RemoteAPI/class-base-endpoint-remote.php
  src/RemoteAPI/class-referrers-post-detail-api.php
  src/RemoteAPI/class-related-api.php
  src/RemoteAPI/class-validate-api.php
  src/RemoteAPI/content-suggestions/class-content-suggestions-base-api.php
  src/RemoteAPI/content-suggestions/class-write-title-api.php
  src/class-parsely.php
  src/content-helper/common/content-helper-error.tsx
  src/content-helper/common/css/variables.scss
  src/content-helper/editor-sidebar/editor-sidebar.scss
  src/content-helper/editor-sidebar/editor-sidebar.tsx
  src/content-helper/editor-sidebar/title-suggestions/component-title-suggestion.tsx
  src/content-helper/editor-sidebar/title-suggestions/component.tsx
  src/content-helper/editor-sidebar/title-suggestions/provider.ts
  src/content-helper/editor-sidebar/title-suggestions/store.ts
  src/content-helper/editor-sidebar/title-suggestions/types.ts
  tests/Integration/RemoteAPI/content-suggestions/WriteTitleAPITest.php
  wp-parsely.php
Labels: Changelog: Added, Feature: Content Helper

#1758 Add telemetry (optional and off by default)
  src/Telemetry/Events/recommended-widget.php
  src/Telemetry/Events/settings.php
  src/Telemetry/Tracks/class-tracks-event.php
  src/Telemetry/Tracks/class-tracks-pixel.php
  src/Telemetry/Tracks/class-tracks.php
  src/Telemetry/class-telemetry-system.php
  src/Telemetry/telemetry-init.php
  src/Utils/utils.php
  wp-parsely.php
Labels: Component: PHP, Changelog: Added

#2020 Add Content Helper client-side events tracking in optional telemetry
  build/content-helper/dashboard-widget.asset.php
  build/content-helper/dashboard-widget.js
  build/content-helper/editor-sidebar.asset.php
  build/content-helper/editor-sidebar.js
  build/telemetry.asset.php
  build/telemetry.js
  package-lock.json
  package.json
  src/Telemetry/Tracks/class-tracks.php
  src/content-helper/dashboard-widget/components/top-posts.tsx
  src/content-helper/dashboard-widget/dashboard-widget.tsx
  src/content-helper/editor-sidebar/editor-sidebar.tsx
  src/js/telemetry/block-change.tsx
  src/js/telemetry/init.ts
  src/js/telemetry/telemetry.ts
  webpack.config.js
Labels: Component: JavaScript, Changelog: Added

#2031 Site Health Info: Remove unneeded options
  src/UI/class-site-health.php
Labels: Changelog: Changed

#2034 Docs: Fix reference to Site Editing
  README.md
Labels: Type: Documentation

#2025 Move internal documentation to docs directory
  CONTRIBUTING.md
  docs/CONTRIBUTING.md
  docs/RELEASING.md
  docs/SECURITY.md
  docs/TESTING.md
  docs/WINDOWS.md
  tests/e2e/README.md
Labels: Type: Maintenance
