Repository Parsely/wp-parsely, pull requests merged in 2024-10, with the labels that each got.

#2815 Bump @wordpress/editor from 14.7.0 to 14.8.3
  package-lock.json
  package.json
Labels: Component: Dependencies, javascript

#2816 Bump @wordpress/edit-post from 8.7.0 to 8.8.3
  package-lock.json
  package.json
Labels: Component: Dependencies, javascript

#2817 Update package-lock.json
  build/recommended-widget.asset.php
  build/recommended-widget.js
  package-lock.json
Labels: Component: Dependencies, javascript

#2812 REST API Refactor: Apply fixes/suggestions from the other PRs
  src/content-helper/dashboard-widget/class-dashboard-widget.php
  src/content-helper/editor-sidebar/class-editor-sidebar.php
  src/rest-api/class-base-api-controller.php
  src/rest-api/class-base-endpoint.php
  src/rest-api/content-helper/class-content-helper-controller.php
  src/rest-api/content-helper/class-endpoint-excerpt-generator.php
  src/rest-api/content-helper/class-endpoint-smart-linking.php
  src/rest-api/content-helper/class-endpoint-title-suggestions.php
  src/rest-api/settings/class-endpoint-dashboard-widget-settings.php
  src/rest-api/settings/class-endpoint-editor-sidebar-settings.php
  src/rest-api/settings/class-settings-controller.php
  src/rest-api/stats/class-endpoint-post.php
  src/rest-api/stats/class-endpoint-posts.php
  src/rest-api/stats/class-endpoint-related.php
  src/rest-api/stats/class-stats-controller.php
  tests/Integration/RestAPI/BaseAPIControllerTest.php
  tests/Integration/RestAPI/BaseEndpointTest.php
  tests/Integration/RestAPI/ContentHelper/ContentHelperControllerTest.php
Labels: Type: Maintenance

#2839 Bump @wordpress/editor from 14.8.3 to 14.9.0
  package-lock.json
  package.json
Labels: Component: Dependencies, javascript

#2840 Bump @wordpress/edit-post from 8.8.3 to 8.9.0
  package-lock.json
  package.json
Labels: Component: Dependencies, javascript

#2841 Update WordPress typing packages
  package-lock.json
  package.json
  src/@types/gutenberg/types.ts
Labels: Component: Dependencies, javascript

#2847 Fix AMP validation issues
  src/Integrations/class-amp.php
Labels: Changelog: Fixed

#2845 PCH Sidebar: Update documentation links
  build/content-helper/editor-sidebar.asset.php
  build/content-helper/editor-sidebar.js
  src/content-helper/editor-sidebar/smart-linking/component.tsx
  src/content-helper/editor-sidebar/title-suggestions/component.tsx
Labels: Type: Maintenance, Feature: Content Helper

#2849 Remove repeated-metas.php and move class-meta-renderer.php
  src/Metadata/class-metadata-renderer.php
  views/repeated-metas.php
Labels: Type: Maintenance, Type: Refactoring

#2877 Move Settings page to src/UI/
  package.json
  phpstan.neon
  rector.php
  src/UI/class-settings-page.php
  src/UI/settings-page.php
  tests/Integration/UI/SettingsPageTest.php
Labels: Type: Maintenance

#2885 PCH Refactor: Update integration tests
  src/content-helper/editor-sidebar/class-editor-sidebar.php
  src/rest-api/stats/class-endpoint-post.php
  src/services/class-base-service-endpoint.php
  src/services/class-cached-service-endpoint.php
  src/services/content-api/class-content-api-service.php
  src/services/content-api/endpoints/class-endpoint-analytics-posts.php
  src/services/suggestions-api/endpoints/class-suggestions-api-base-endpoint.php
  tests/Integration/ContentHelper/ContentHelperDashboardWidgetTest.php
  tests/Integration/ContentHelper/ContentHelperFeatureTest.php
  tests/Integration/ContentHelper/ContentHelperPostListStatsTest.php
  tests/Integration/RemoteAPI/AnalyticsPostsRemoteAPITest.php
  tests/Integration/RemoteAPI/BaseRemoteAPITest.php
  tests/Integration/RemoteAPI/ContentSuggestions/BaseContentSuggestionsAPITest.php
  tests/Integration/RemoteAPI/ContentSuggestions/SuggestBriefAPITest.php
  tests/Integration/RemoteAPI/RelatedRemoteAPITest.php
  tests/Integration/RestAPI/BaseAPIControllerTest.php
  tests/Integration/RestAPI/BaseEndpointTest.php
  tests/Integration/RestAPI/ContentHelper/ContentHelperControllerTest.php
  tests/Integration/RestAPI/ContentHelper/ContentHelperFeatureTestTrait.php
  tests/Integration/RestAPI/ContentHelper/EndpointExcerptGeneratorTest.php
  tests/Integration/RestAPI/ContentHelper/EndpointSmartLinkingTest.php
  tests/Integration/RestAPI/ContentHelper/EndpointTitleSuggestionsTest.php
  tests/Integration/RestAPI/Stats/EndpointPostTest.php
  tests/Integration/RestAPI/Stats/EndpointPostsTest.php
  tests/Integration/RestAPI/Stats/EndpointRelatedTest.php
  tests/Integration/Services/BaseAPIServiceTestCase.php
  tests/Integration/Services/BaseServiceEndpointTestCase.php
  tests/Integration/Services/ContentAPI/ContentApiServiceTestCase.php
  tests/Integration/Services/ContentAPI/Endpoints/ContentAPIBaseEndpointTestCase.php
  tests/Integration/Services/ContentAPI/Endpoints/EndpointAnalyticsPostsTest.php
  tests/Integration/Services/ContentAPI/Endpoints/EndpointRelatedTest.php
  tests/Integration/Services/SuggestionsAPI/Endpoints/EndpointSuggestBriefTest.php
  tests/Integration/Services/SuggestionsAPI/Endpoints/EndpointSuggestHeadlineTest.php
  tests/Integration/Services/SuggestionsAPI/Endpoints/EndpointSuggestLinkedReferenceTest.php
  tests/Integration/Services/SuggestionsAPI/Endpoints/SuggestionsAPIBaseEndpointTestCase.php
  tests/Integration/Services/SuggestionsAPI/SuggestionsApiServiceTestCase.php
  tests/Traits/TestsReflection.php
Labels: Type: Maintenance, Type: Refactoring

#2890 PCH Excerpt Suggestions: Add persona and tone settings
  build/content-helper/editor-sidebar-rtl.css
  build/content-helper/editor-sidebar.asset.php
  build/content-helper/editor-sidebar.css
  build/content-helper/editor-sidebar.js
  build/content-helper/excerpt-generator-rtl.css
  build/content-helper/excerpt-generator.asset.php
  build/content-helper/excerpt-generator.css
  build/content-helper/excerpt-generator.js
  src/UI/class-settings-page.php
  src/class-permissions.php
  src/content-helper/common/css/common.scss
  src/content-helper/common/settings/types/index.ts
  src/content-helper/common/settings/types/sidebar-settings.d.ts
  src/content-helper/common/utils/permissions.ts
  src/content-helper/editor-sidebar/class-editor-sidebar-feature.php
  src/content-helper/editor-sidebar/class-editor-sidebar.php
  src/content-helper/editor-sidebar/editor-sidebar.tsx
  src/content-helper/editor-sidebar/excerpt-suggestions/class-excerpt-suggestions.php
  src/content-helper/editor-sidebar/excerpt-suggestions/component-panel-settings.tsx
  src/content-helper/editor-sidebar/excerpt-suggestions/component-panel.tsx
  src/content-helper/editor-sidebar/excerpt-suggestions/excerpt-suggestions.scss
  src/content-helper/editor-sidebar/excerpt-suggestions/excerpt-suggestions.tsx
  src/content-helper/editor-sidebar/excerpt-suggestions/provider.ts
  src/content-helper/editor-sidebar/smart-linking/class-smart-linking.php
  src/content-helper/editor-sidebar/title-suggestions/title-suggestions.scss
  src/content-helper/excerpt-generator/class-excerpt-generator.php
  src/rest-api/settings/class-endpoint-editor-sidebar-settings.php
  src/rest-api/settings/class-endpoint-excerpt-suggestions-settings.php
  tests/Integration/ContentHelper/ContentHelperExcerptSuggestionsTest.php
  tests/Integration/ContentHelper/ContentHelperFeatureTest.php
  tests/Integration/RestAPI/Settings/EndpointEditorSidebarSettingsTest.php
  webpack.config.js
  wp-parsely.php
Labels: Type: Enhancement, Changelog: Added, Feature: Content Helper

#2811 PCH Excerpt Suggestions: Add feature to the PCH sidebar
  build/content-helper/editor-sidebar-rtl.css
  build/content-helper/editor-sidebar.asset.php
  build/content-helper/editor-sidebar.css
  build/content-helper/editor-sidebar.js
  src/content-helper/editor-sidebar/class-editor-sidebar.php
  src/content-helper/editor-sidebar/editor-sidebar.tsx
  src/content-helper/editor-sidebar/excerpt-suggestions/component-panel.tsx
  src/content-helper/editor-sidebar/excerpt-suggestions/excerpt-suggestions.scss
  src/content-helper/editor-sidebar/excerpt-suggestions/excerpt-suggestions.tsx
  src/content-helper/editor-sidebar/smart-linking/component.tsx
  src/content-helper/editor-sidebar/tabs/sidebar-tools-tab.tsx
Labels: Changelog: Added

#2893 PCH Performance Panel: Show stats for posts with a trackable status
  build/content-helper/editor-sidebar.asset.php
  build/content-helper/editor-sidebar.js
  src/@types/assets/window.d.ts
  src/class-parsely.php
  src/content-helper/editor-sidebar/class-editor-sidebar.php
  src/content-helper/editor-sidebar/performance-stats/provider.ts
Labels: Changelog: Changed
