Repository Parsely/wp-parsely, pull requests merged in 2024-09, with the labels that each got.

#2731 REST API Refactor: Base classes and Content Helper namespace implementation
  build/content-helper/editor-sidebar.asset.php
  build/content-helper/editor-sidebar.js
  build/content-helper/excerpt-generator.asset.php
  build/content-helper/excerpt-generator.js
  src/Endpoints/content-suggestions/class-suggest-brief-api-proxy.php
  src/Endpoints/content-suggestions/class-suggest-headline-api-proxy.php
  src/Endpoints/content-suggestions/class-suggest-linked-reference-api-proxy.php
  src/Models/class-smart-link.php
  src/content-helper/editor-sidebar/smart-linking/provider.ts
  src/content-helper/editor-sidebar/title-suggestions/provider.ts
  src/content-helper/excerpt-generator/provider.ts
  src/rest-api/class-base-api-controller.php
  src/rest-api/class-base-endpoint.php
  src/rest-api/class-rest-api-controller.php
  src/rest-api/content-helper/class-content-helper-controller.php
  src/rest-api/content-helper/class-endpoint-excerpt-generator.php
  src/rest-api/content-helper/class-endpoint-smart-linking.php
  src/rest-api/content-helper/class-endpoint-title-suggestions.php
  src/rest-api/content-helper/trait-content-helper-feature.php
  tests/Integration/ContentHelper/ContentHelperDashboardWidgetTest.php
  tests/Integration/ContentHelper/ContentHelperFeatureTest.php
  tests/Integration/ContentHelper/ContentHelperPostListStatsTest.php
  tests/Integration/RestAPI/BaseAPIControllerTest.php
  tests/Integration/RestAPI/BaseEndpointTest.php
  tests/Integration/RestAPI/ContentHelper/ContentHelperControllerTest.php
  tests/Integration/RestAPI/ContentHelper/ContentHelperFeatureTestTrait.php
  tests/Integration/RestAPI/ContentHelper/EndpointExcerptGeneratorTest.php
  tests/Integration/RestAPI/ContentHelper/EndpointSmartLinkingTest.php
  tests/Integration/RestAPI/ContentHelper/EndpointTitleSuggestionsTest.php
  tests/Integration/RestAPI/RestAPIControllerTest.php
  tests/Integration/ScriptsTest.php
  tests/Integration/TestCase.php
  wp-parsely.php
Labels: Type: Maintenance, Changelog: Changed

#2737 class-base-endpoint.php: Fix incorrect whitespace
  src/Endpoints/class-base-endpoint.php
Labels: Type: Maintenance

#2735 REST API Refactor: Settings namespace implementation
  build/content-helper/dashboard-widget.asset.php
  build/content-helper/dashboard-widget.js
  build/content-helper/editor-sidebar.asset.php
  build/content-helper/editor-sidebar.js
  src/Endpoints/class-base-api-proxy.php
  src/RemoteAPI/content-suggestions/class-content-suggestions-base-api.php
  src/content-helper/common/class-content-helper-feature.php
  src/content-helper/common/settings/provider.tsx
  src/content-helper/dashboard-widget/class-dashboard-widget.php
  src/content-helper/dashboard-widget/dashboard-widget.tsx
  src/content-helper/editor-sidebar/class-editor-sidebar.php
  src/content-helper/editor-sidebar/editor-sidebar.tsx
  src/content-helper/editor-sidebar/smart-linking/smart-linking.tsx
  src/rest-api/class-rest-api-controller.php
  src/rest-api/settings/class-base-settings-endpoint.php
  src/rest-api/settings/class-endpoint-dashboard-widget-settings.php
  src/rest-api/settings/class-endpoint-editor-sidebar-settings.php
  src/rest-api/settings/class-settings-controller.php
  tests/Integration/Endpoints/Proxy/BaseProxyEndpointTest.php
  tests/Integration/Endpoints/RestMetadataTest.php
  tests/Integration/Endpoints/UserMeta/BaseUserMetaEndpointTest.php
  tests/Integration/Endpoints/UserMeta/DashboardWidgetSettingsEndpointTest.php
  tests/Integration/Endpoints/UserMeta/EditorSidebarSettingsEndpointTest.php
  tests/Integration/RestAPI/BaseEndpointTest.php
  tests/Integration/RestAPI/Settings/BaseSettingsEndpointTest.php
  tests/Integration/RestAPI/Settings/EndpointDashboardWidgetSettingsTest.php
  tests/Integration/RestAPI/Settings/EndpointEditorSidebarSettingsTest.php
  wp-parsely.php
Labels: Type: Maintenance, Changelog: Changed

#2733 Add Playwright infrastructure for E2E tests
  .github/workflows/e2e-tests.yml
  jest-e2e.config.js
  package-lock.json
  package.json
  test/e2e/playwright.config.ts
  test/e2e/specs/plugin-action-link.spec.ts
  tests/e2e/specs/plugin-action-link.spec.ts
Labels: Type: Maintenance

#2736 Migrate E2E tests to Playwright
  .github/workflows/e2e-tests.yml
  build/blocks/recommendations/edit.asset.php
  build/blocks/recommendations/edit.js
  build/blocks/recommendations/view.asset.php
  build/blocks/recommendations/view.js
  docs/TESTING.md
  jest-e2e.config.js
  package-lock.json
  package.json
  src/blocks/recommendations/components/parsely-recommendations.tsx
  test/e2e/specs/plugin-action-link.spec.ts
  tests/e2e/playwright.config.ts
  tests/e2e/specs/activation-flow.spec.ts
  tests/e2e/specs/blocks/recommendations/errors.spec.ts
  tests/e2e/specs/blocks/recommendations/settings.spec.ts
  tests/e2e/specs/browse-logo-button.spec.ts
  tests/e2e/specs/content-helper/errors.spec.ts
  tests/e2e/specs/content-helper/related-posts-panel-filters.spec.ts
  tests/e2e/specs/content-helper/top-bar-icon.spec.ts
  tests/e2e/specs/front-end-metadata.spec.ts
  tests/e2e/specs/front-end-tracker.spec.ts
  tests/e2e/specs/plugin-action-link.spec.ts
  tests/e2e/specs/recommended-widget.spec.ts
  tests/e2e/specs/settings-track-post-types-as.spec.ts
  tests/e2e/utils.ts
Labels: Type: Maintenance, Type: Refactoring, Changelog: Changed

#2739 .phpcs.xml.dist: Update PHP and WordPress version numbers
  .phpcs.xml.dist
Labels: Type: Maintenance

#2769 Bump @wordpress/editor from 14.5.0 to 14.7.0
  package-lock.json
  package.json
Labels: Component: Dependencies, javascript

#2770 Bump @wordpress/edit-post from 8.5.0 to 8.7.0
  package-lock.json
  package.json
Labels: Component: Dependencies, javascript

#2783 Update @wordpress/compose version number
  package-lock.json
  package.json
Labels: Type: Maintenance, Component: Dependencies, javascript

#2786 Fix vulnerable dependencies
  package-lock.json
  package.json
Labels: Component: Dependencies, javascript
