Repository Parsely/wp-parsely, pull requests merged in 2024-04, with the labels that each got.

#2350 README.md: Update some documentation links
  README.md
Labels: Type: Maintenance

#2351 PCH: Update Settings API structure
  bin/install-wp-tests.sh
  build/content-helper/editor-sidebar.asset.php
  build/content-helper/editor-sidebar.js
  jest.config.js
  src/Endpoints/user-meta/class-base-endpoint-user-meta.php
  src/Endpoints/user-meta/class-editor-sidebar-settings-endpoint.php
  src/content-helper/common/settings/types/index.ts
  src/content-helper/common/settings/types/sidebar-settings.d.ts
  src/content-helper/editor-sidebar/editor-sidebar.tsx
  src/content-helper/editor-sidebar/performance-details/component-panel-overview.tsx
  src/content-helper/editor-sidebar/performance-details/component.tsx
  src/content-helper/editor-sidebar/related-posts/component.tsx
  src/content-helper/editor-sidebar/related-posts/hooks.ts
  src/content-helper/editor-sidebar/smart-linking/component-settings.tsx
  src/content-helper/editor-sidebar/smart-linking/component.tsx
  src/content-helper/editor-sidebar/smart-linking/smart-linking.tsx
  src/content-helper/editor-sidebar/tabs/sidebar-tools-tab.tsx
  src/content-helper/editor-sidebar/title-suggestions/component-settings.tsx
  src/content-helper/editor-sidebar/title-suggestions/component.tsx
  tests/Integration/BaseUserMetaEndpointTest.php
  tests/Integration/Endpoints/EditorSidebarSettingsEndpointTest.php
  tests/js/content-helper/structure.test.tsx
Labels: Changelog: Changed, Feature: Content Helper

#2354 release-template.md: Add link for smoke testing
  .github/ISSUE_TEMPLATE/release-template.md
Labels: Type: Maintenance

#2355 release-template.md: Update for clarity
  .github/ISSUE_TEMPLATE/release-template.md
Labels: Type: Maintenance

#2353 PCH: Rename Performance Details to Performance Stats
  build/content-helper/editor-sidebar.asset.php
  build/content-helper/editor-sidebar.js
  src/content-helper/editor-sidebar/performance-stats/component-panel-categories.tsx
  src/content-helper/editor-sidebar/performance-stats/component-panel-overview.tsx
  src/content-helper/editor-sidebar/performance-stats/component-panel-referrers.tsx
  src/content-helper/editor-sidebar/performance-stats/component-panel.tsx
  src/content-helper/editor-sidebar/performance-stats/component.tsx
  src/content-helper/editor-sidebar/performance-stats/model.ts
  src/content-helper/editor-sidebar/performance-stats/performance-stats.scss
  src/content-helper/editor-sidebar/performance-stats/provider.ts
  src/content-helper/editor-sidebar/tabs/sidebar-performance-tab.tsx
Labels: Type: Maintenance

#2356 README.md: Update "Tested up to" to 6.5
  README.md
Labels: Type: Maintenance

#2386 PCH Smart Linking: Allow API retry when there are upstream errors
  build/admin-settings.asset.php
  build/admin-settings.css
  build/content-helper/dashboard-widget.asset.php
  build/content-helper/dashboard-widget.css
  build/content-helper/dashboard-widget.js
  build/content-helper/editor-sidebar.asset.php
  build/content-helper/editor-sidebar.css
  build/content-helper/editor-sidebar.js
  build/content-helper/excerpt-generator.asset.php
  build/content-helper/excerpt-generator.css
  build/content-helper/excerpt-generator.js
  src/content-helper/common/content-helper-error.tsx
  src/content-helper/common/css/variables.scss
  src/content-helper/editor-sidebar/smart-linking/component-block-overlay.tsx
  src/content-helper/editor-sidebar/smart-linking/component.tsx
  src/content-helper/editor-sidebar/smart-linking/provider.ts
  src/content-helper/editor-sidebar/smart-linking/smart-linking.scss
  src/content-helper/editor-sidebar/smart-linking/store.ts
Labels: Changelog: Changed, Feature: Content Helper

#2397 EmptyCredentialsMessage: Fix empty error
  build/content-helper/dashboard-widget.asset.php
  build/content-helper/dashboard-widget.js
  build/content-helper/editor-sidebar.asset.php
  build/content-helper/editor-sidebar.js
  build/content-helper/excerpt-generator.asset.php
  build/content-helper/excerpt-generator.js
  src/content-helper/common/content-helper-error-message.tsx
Labels: Changelog: Fixed

#2398 Fix removeEditorPanel() deprecation message in WordPress 6.5
  build/content-helper/excerpt-generator.asset.php
  build/content-helper/excerpt-generator.js
  src/content-helper/excerpt-generator/excerpt-generator.tsx
Labels: Type: Maintenance, Changelog: Fixed

#2314 CSS: Remove fallback values from var() calls
  build/admin-settings.asset.php
  build/admin-settings.css
  build/content-helper/dashboard-widget.asset.php
  build/content-helper/dashboard-widget.css
  build/content-helper/editor-sidebar.asset.php
  build/content-helper/editor-sidebar.css
  build/content-helper/excerpt-generator.asset.php
  build/content-helper/excerpt-generator.css
  src/content-helper/common/components/input-range/style.scss
  src/content-helper/common/components/persona-selector/style.scss
  src/content-helper/common/components/tone-selector/style.scss
  src/content-helper/common/css/common.scss
  src/content-helper/common/css/variables.scss
  src/content-helper/editor-sidebar/editor-sidebar.scss
  src/content-helper/editor-sidebar/performance-stats/performance-stats.scss
  src/content-helper/editor-sidebar/related-posts/related-posts.scss
  src/content-helper/editor-sidebar/smart-linking/smart-linking.scss
  src/content-helper/editor-sidebar/title-suggestions/title-suggestions.scss
  src/content-helper/excerpt-generator/excerpt-generator.scss
Labels: Type: Maintenance

#2402 TypeScript DocBlocks: Remove spaces in braces
  src/content-helper/common/settings/provider.tsx
  src/content-helper/common/utils/functions.ts
  src/content-helper/editor-sidebar/performance-stats/component-panel-categories.tsx
  src/content-helper/editor-sidebar/performance-stats/component-panel-overview.tsx
  src/content-helper/editor-sidebar/performance-stats/component-panel-referrers.tsx
  src/content-helper/editor-sidebar/performance-stats/component-panel.tsx
  src/content-helper/editor-sidebar/performance-stats/component.tsx
  src/content-helper/editor-sidebar/related-posts/component-item.tsx
  src/content-helper/editor-sidebar/related-posts/hooks.ts
  src/content-helper/editor-sidebar/smart-linking/component.tsx
  src/content-helper/editor-sidebar/tabs/sidebar-performance-tab.tsx
  src/content-helper/editor-sidebar/tabs/sidebar-tools-tab.tsx
  src/content-helper/editor-sidebar/title-suggestions/provider.ts
  tests/e2e/specs/content-helper/top-bar-icon.spec.ts
  tests/js/content-helper/structure.test.tsx
Labels: Type: Maintenance

#2429 Remove unnecessary empty line
  src/content-helper/editor-sidebar/related-posts/hooks.ts
Labels: Type: Maintenance

#2428 PCH Editor Sidebar: Update isDismissible in Notices
  build/content-helper/editor-sidebar.asset.php
  build/content-helper/editor-sidebar.js
  build/content-helper/excerpt-generator.asset.php
  build/content-helper/excerpt-generator.js
  src/content-helper/editor-sidebar/related-posts/component-item.tsx
  src/content-helper/editor-sidebar/smart-linking/component.tsx
  src/content-helper/editor-sidebar/title-suggestions/component.tsx
  src/content-helper/excerpt-generator/components/excerpt-panel.tsx
Labels: Changelog: Changed

#2401 PCH: Enhance Request Handling in Provider Classes
  build/content-helper/dashboard-widget.asset.php
  build/content-helper/dashboard-widget.js
  build/content-helper/editor-sidebar.asset.php
  build/content-helper/editor-sidebar.js
  src/content-helper/common/base-provider.tsx
  src/content-helper/dashboard-widget/components/top-posts.tsx
  src/content-helper/dashboard-widget/provider.ts
  src/content-helper/editor-sidebar/performance-stats/component.tsx
  src/content-helper/editor-sidebar/performance-stats/provider.ts
  src/content-helper/editor-sidebar/related-posts/component.tsx
  src/content-helper/editor-sidebar/related-posts/provider.ts
  src/content-helper/editor-sidebar/smart-linking/component-block-overlay.tsx
  src/content-helper/editor-sidebar/smart-linking/component.tsx
  src/content-helper/editor-sidebar/smart-linking/provider.ts
  src/content-helper/editor-sidebar/title-suggestions/component.tsx
  src/content-helper/editor-sidebar/title-suggestions/provider.ts
  tests/js/content-helper/structure.test.tsx
Labels: Changelog: Changed

#2431 PCH: Strip all tags from the content sent to the API
  src/RemoteAPI/content-suggestions/class-suggest-brief-api.php
  src/RemoteAPI/content-suggestions/class-suggest-headline-api.php
  src/RemoteAPI/content-suggestions/class-suggest-linked-reference-api.php
Labels: Changelog: Changed
