Repository Parsely/wp-parsely, pull requests merged in 2024-08, with the labels that each got.

#2685 PCH Smart Linking: Fix issue with undefined 'wpParselySmartLinkingAllowedBlocks'
  build/content-helper/editor-sidebar.asset.php
  build/content-helper/editor-sidebar.js
  src/content-helper/editor-sidebar/smart-linking/smart-linking.tsx
Labels: Changelog: Fixed

#2722 Bump axios from 1.7.2 to 1.7.4
  package-lock.json
Labels: Component: Dependencies, javascript

#2723 Fix current_user_can_use_pch_feature() issues
  src/class-permissions.php
Labels: Changelog: Fixed

#2730 Settings_Page: Remove duplicate phpstan-import-type declaration
  src/UI/class-settings-page.php
Labels: Type: Maintenance

#2729 Add integration tests for the Permissions class
  tests/Integration/PermissionsTest.php
Labels: Type: Maintenance
