Repository Parsely/wp-parsely, pull requests merged in 2024-06, with the labels that each got.

#2537 Revert to using babel-preset-default v7
  package-lock.json
  package.json
Labels: Component: Dependencies, javascript

#2540 Update data, core-data and editor WordPress packages
  build/content-helper/editor-sidebar.asset.php
  build/content-helper/editor-sidebar.js
  build/content-helper/excerpt-generator.asset.php
  build/content-helper/excerpt-generator.js
  package-lock.json
  package.json
  src/@types/gutenberg/types.ts
  src/content-helper/editor-sidebar/related-posts/component.tsx
  src/content-helper/editor-sidebar/related-posts/hooks.ts
  src/content-helper/editor-sidebar/smart-linking/component-block-overlay.tsx
  src/content-helper/editor-sidebar/smart-linking/component.tsx
  src/content-helper/editor-sidebar/title-suggestions/component-title-suggestion.tsx
  src/content-helper/editor-sidebar/title-suggestions/component.tsx
  src/content-helper/excerpt-generator/excerpt-generator.tsx
  src/js/telemetry/block-change.tsx
Labels: Component: Dependencies, javascript

#2541 Update minimum node and npm versions
  .nvmrc
  package-lock.json
  package.json
Labels: Type: Maintenance, Component: Dependencies

#2543 Update the Node.js GitHub Action workflow to respect .nvmrc version
  .github/workflows/node.js.yml
  .nvmrc
Labels: Type: Maintenance

#2507 PCH Smart Linking: Implement Smart Links Reviewing step
  build/admin-settings-rtl.css
  build/admin-settings.asset.php
  build/admin-settings.css
  build/content-helper/dashboard-widget-rtl.css
  build/content-helper/dashboard-widget.asset.php
  build/content-helper/dashboard-widget.css
  build/content-helper/editor-sidebar-rtl.css
  build/content-helper/editor-sidebar.asset.php
  build/content-helper/editor-sidebar.css
  build/content-helper/editor-sidebar.js
  build/content-helper/excerpt-generator-rtl.css
  build/content-helper/excerpt-generator.asset.php
  build/content-helper/excerpt-generator.css
  jest.config.js
  jest.setup.js
  phpstan.neon
  src/@types/gutenberg/types.ts
  src/Endpoints/class-base-endpoint.php
  src/Endpoints/content-helper/class-smart-linking-endpoint.php
  src/Endpoints/content-suggestions/class-suggest-linked-reference-api-proxy.php
  src/Endpoints/user-meta/class-base-endpoint-user-meta.php
  src/Models/class-base-model.php
  src/Models/class-smart-link.php
  src/RemoteAPI/class-analytics-post-detail-api.php
  src/RemoteAPI/class-analytics-posts-api.php
  src/RemoteAPI/class-referrers-post-detail-api.php
  src/RemoteAPI/class-related-api.php
  src/RemoteAPI/class-remote-api-cache.php
  src/RemoteAPI/class-validate-api.php
  src/RemoteAPI/content-suggestions/class-content-suggestions-base-api.php
  src/RemoteAPI/content-suggestions/class-link-suggestion.php
  src/RemoteAPI/content-suggestions/class-suggest-linked-reference-api.php
  src/RemoteAPI/interface-remote-api.php
  src/content-helper/common/base-provider.tsx
  src/content-helper/common/css/variables.scss
  src/content-helper/common/icons/ai-icon.tsx
  src/content-helper/editor-sidebar/editor-sidebar.tsx
  src/content-helper/editor-sidebar/smart-linking/component-block-overlay.tsx
  src/content-helper/editor-sidebar/smart-linking/component-link-monitor.tsx
  src/content-helper/editor-sidebar/smart-linking/component.tsx
  src/content-helper/editor-sidebar/smart-linking/hooks.ts
  src/content-helper/editor-sidebar/smart-linking/provider.ts
  src/content-helper/editor-sidebar/smart-linking/review-modal/component-modal.tsx
  src/content-helper/editor-sidebar/smart-linking/review-modal/component-sidebar.tsx
  src/content-helper/editor-sidebar/smart-linking/review-modal/component-suggestion.tsx
  src/content-helper/editor-sidebar/smart-linking/smart-linking.scss
  src/content-helper/editor-sidebar/smart-linking/store.ts
  src/content-helper/editor-sidebar/smart-linking/utils.ts
  tests/Integration/BaseUserMetaEndpointTest.php
  tests/Integration/ProxyEndpointTest.php
  tests/Integration/RemoteAPI/content-suggestions/SuggestLinkedReferenceAPITest.php
  tests/js/content-helper/smart-linking.test.tsx
  wp-parsely.php
Labels: Component: JavaScript, Changelog: Added, Feature: Content Helper

#2542 Use React.JSX instead of JSX
  src/blocks/recommendations/components/parsely-recommendations-fetcher.tsx
  src/blocks/recommendations/components/parsely-recommendations.tsx
  src/content-helper/common/components/input-range/component.tsx
  src/content-helper/common/components/persona-selector/component.tsx
  src/content-helper/common/components/tone-selector/component.tsx
  src/content-helper/common/content-helper-error-message.tsx
  src/content-helper/common/content-helper-error.tsx
  src/content-helper/common/icons/ai-icon.tsx
  src/content-helper/common/select.tsx
  src/content-helper/common/settings/provider.tsx
  src/content-helper/common/utils/post.tsx
  src/content-helper/common/verify-credentials.tsx
  src/content-helper/dashboard-widget/components/top-posts-list-item.tsx
  src/content-helper/dashboard-widget/components/top-posts.tsx
  src/content-helper/editor-sidebar/editor-sidebar.tsx
  src/content-helper/editor-sidebar/performance-stats/component-panel-categories.tsx
  src/content-helper/editor-sidebar/performance-stats/component-panel-overview.tsx
  src/content-helper/editor-sidebar/performance-stats/component-panel-referrers.tsx
  src/content-helper/editor-sidebar/performance-stats/component-panel.tsx
  src/content-helper/editor-sidebar/performance-stats/component.tsx
  src/content-helper/editor-sidebar/related-posts/component-filter-settings.tsx
  src/content-helper/editor-sidebar/related-posts/component-item.tsx
  src/content-helper/editor-sidebar/related-posts/component.tsx
  src/content-helper/editor-sidebar/smart-linking/component-block-overlay.tsx
  src/content-helper/editor-sidebar/smart-linking/component-settings.tsx
  src/content-helper/editor-sidebar/smart-linking/component.tsx
  src/content-helper/editor-sidebar/smart-linking/review-modal/component-modal.tsx
  src/content-helper/editor-sidebar/smart-linking/review-modal/component-sidebar.tsx
  src/content-helper/editor-sidebar/smart-linking/review-modal/component-suggestion.tsx
  src/content-helper/editor-sidebar/tabs/sidebar-performance-tab.tsx
  src/content-helper/editor-sidebar/tabs/sidebar-tools-tab.tsx
  src/content-helper/editor-sidebar/title-suggestions/component-pinned.tsx
  src/content-helper/editor-sidebar/title-suggestions/component-settings.tsx
  src/content-helper/editor-sidebar/title-suggestions/component-suggestions.tsx
  src/content-helper/editor-sidebar/title-suggestions/component-title-suggestion.tsx
  src/content-helper/editor-sidebar/title-suggestions/component.tsx
  src/content-helper/excerpt-generator/components/excerpt-panel.tsx
  tests/js/content-helper/post-list-stats.test.tsx
Labels: Type: Maintenance

#2547 PCH Smart Linking: Fix issue when processing a single block
  build/content-helper/editor-sidebar.asset.php
  build/content-helper/editor-sidebar.js
  src/content-helper/editor-sidebar/smart-linking/component.tsx
Labels: Component: JavaScript, Changelog: Fixed, Feature: Content Helper

#2548 PCH Smart Linking: Fix issue with focus hijacking
  build/content-helper/editor-sidebar.asset.php
  build/content-helper/editor-sidebar.js
  src/content-helper/editor-sidebar/smart-linking/review-modal/component-sidebar.tsx
Labels: Changelog: Fixed

#2569 PCH Smart Linking: Fix issue with pending Smart Links being saved on post auto save
  build/content-helper/editor-sidebar.asset.php
  build/content-helper/editor-sidebar.js
  src/@types/gutenberg/types.ts
  src/Models/class-smart-link.php
  src/content-helper/editor-sidebar/smart-linking/component.tsx
  src/content-helper/editor-sidebar/smart-linking/hooks.ts
  src/content-helper/editor-sidebar/smart-linking/provider.ts
  src/content-helper/editor-sidebar/smart-linking/review-modal/component-modal.tsx
Labels: Changelog: Fixed, Feature: Content Helper

#2570 PCH Smart Linking: Prevent Smart Linking from running on Freeform (Classic) blocks
  build/content-helper/editor-sidebar.asset.php
  build/content-helper/editor-sidebar.js
  src/content-helper/editor-sidebar/smart-linking/component.tsx
Labels: Changelog: Fixed

#2571 PCH Smart Linking: Prevent duplicate Smart Links
  build/content-helper/editor-sidebar.asset.php
  build/content-helper/editor-sidebar.js
  src/content-helper/editor-sidebar/smart-linking/component.tsx
  src/content-helper/editor-sidebar/smart-linking/utils.ts
Labels: Changelog: Fixed

#2553 PCH Smart Links: Add Inbound Smart Links support
  build/content-helper/editor-sidebar-rtl.css
  build/content-helper/editor-sidebar.asset.php
  build/content-helper/editor-sidebar.css
  build/content-helper/editor-sidebar.js
  build/telemetry.asset.php
  build/telemetry.js
  composer.json
  src/Models/class-inbound-smart-link.php
  src/Models/class-smart-link.php
  src/RemoteAPI/content-suggestions/class-suggest-linked-reference-api.php
  src/content-helper/common/utils/functions.ts
  src/content-helper/editor-sidebar/smart-linking/component.tsx
  src/content-helper/editor-sidebar/smart-linking/provider.ts
  src/content-helper/editor-sidebar/smart-linking/review-modal/component-block-preview.tsx
  src/content-helper/editor-sidebar/smart-linking/review-modal/component-inbound-link.tsx
  src/content-helper/editor-sidebar/smart-linking/review-modal/component-modal.tsx
  src/content-helper/editor-sidebar/smart-linking/review-modal/component-sidebar.tsx
  src/content-helper/editor-sidebar/smart-linking/review-modal/component-suggestion.tsx
  src/content-helper/editor-sidebar/smart-linking/smart-linking.scss
  src/content-helper/editor-sidebar/smart-linking/smart-linking.tsx
  src/content-helper/editor-sidebar/smart-linking/store.ts
  src/content-helper/editor-sidebar/smart-linking/utils.ts
  src/js/telemetry/block-change.tsx
  wp-parsely.php
Labels: Changelog: Added, Feature: Content Helper
