Repository Parsely/wp-parsely, pull requests merged in 2024-07, with the labels that each got.

#2600 PCH: Fix non-dismissible Notices
  build/content-helper/editor-sidebar.asset.php
  build/content-helper/editor-sidebar.js
  build/content-helper/excerpt-generator.asset.php
  build/content-helper/excerpt-generator.js
  src/content-helper/editor-sidebar/title-suggestions/component.tsx
  src/content-helper/excerpt-generator/components/excerpt-panel.tsx
Labels: Changelog: Fixed

#2554 Settings page: Add "Content Helper" UI
  build/admin-settings-rtl.css
  build/admin-settings.asset.php
  build/admin-settings.css
  build/admin-settings.js
  phpstan.neon
  src/UI/class-settings-page.php
  src/class-parsely.php
  src/class-permissions.php
  src/css/admin-settings.scss
  src/js/admin-settings.ts
  wp-parsely.php
Labels: Changelog: Added, Feature: Content Helper

#2580 ContentHelperError: Avoid double prefix in error messages
  build/content-helper/dashboard-widget.asset.php
  build/content-helper/dashboard-widget.js
  build/content-helper/editor-sidebar.asset.php
  build/content-helper/editor-sidebar.js
  build/content-helper/excerpt-generator.asset.php
  build/content-helper/excerpt-generator.js
  src/content-helper/common/content-helper-error.tsx
Labels: Changelog: Fixed, Feature: Content Helper

#2579 PCH Sidebar: Show detailed error messages in snackbar Notices
  build/content-helper/dashboard-widget.asset.php
  build/content-helper/dashboard-widget.js
  build/content-helper/editor-sidebar.asset.php
  build/content-helper/editor-sidebar.js
  build/content-helper/excerpt-generator.asset.php
  build/content-helper/excerpt-generator.js
  src/content-helper/common/content-helper-error.tsx
  src/content-helper/editor-sidebar/smart-linking/component.tsx
  src/content-helper/editor-sidebar/title-suggestions/component.tsx
Labels: Changelog: Fixed, Feature: Content Helper

#2578 PCH Sidebar: Move initialization to admin_init
  wp-parsely.php
Labels: Changelog: Changed, Feature: Content Helper

#2604 Content Helper: Implement AI feature permissions
  build/content-helper/dashboard-widget.asset.php
  build/content-helper/dashboard-widget.js
  build/content-helper/editor-sidebar.asset.php
  build/content-helper/editor-sidebar.js
  build/content-helper/excerpt-generator.asset.php
  build/content-helper/excerpt-generator.js
  src/@types/assets/window.d.ts
  src/Endpoints/content-helper/class-smart-linking-endpoint.php
  src/Endpoints/content-suggestions/class-suggest-brief-api-proxy.php
  src/Endpoints/content-suggestions/class-suggest-headline-api-proxy.php
  src/Endpoints/content-suggestions/class-suggest-linked-reference-api-proxy.php
  src/UI/class-settings-page.php
  src/class-parsely.php
  src/class-permissions.php
  src/content-helper/common/class-content-helper-feature.php
  src/content-helper/common/content-helper-error.tsx
  src/content-helper/common/utils/permissions.ts
  src/content-helper/editor-sidebar/editor-sidebar.tsx
  src/content-helper/editor-sidebar/smart-linking/class-smart-linking.php
  src/content-helper/editor-sidebar/smart-linking/component.tsx
  src/content-helper/editor-sidebar/smart-linking/smart-linking.tsx
  src/content-helper/editor-sidebar/tabs/sidebar-tools-tab.tsx
  src/content-helper/excerpt-generator/class-excerpt-generator.php
  tests/Integration/UI/SettingsPageTest.php
Labels: Changelog: Added, Feature: Content Helper

#2601 PCH: Don't show Snackbar Notices for error messages with links
  .eslintrc
  build/content-helper/dashboard-widget.asset.php
  build/content-helper/dashboard-widget.js
  build/content-helper/editor-sidebar.asset.php
  build/content-helper/editor-sidebar.js
  build/content-helper/excerpt-generator.asset.php
  build/content-helper/excerpt-generator.js
  src/content-helper/common/content-helper-error.tsx
  src/content-helper/editor-sidebar/smart-linking/component.tsx
  src/content-helper/editor-sidebar/title-suggestions/component.tsx
Labels: Feature: Content Helper

#2605 PCH Smart Linking: Add additional Telemetry to the new Smart Linking interface
  build/content-helper/editor-sidebar.asset.php
  build/content-helper/editor-sidebar.js
  src/content-helper/editor-sidebar/smart-linking/component.tsx
  src/content-helper/editor-sidebar/smart-linking/review-modal/component-inbound-link.tsx
  src/content-helper/editor-sidebar/smart-linking/review-modal/component-modal.tsx
  src/content-helper/editor-sidebar/smart-linking/review-modal/component-sidebar.tsx
Labels: Changelog: Added

#2606 PCH: Initialize Content Helper features on `rest_api_init`
  wp-parsely.php
Labels: Changelog: Fixed

#2607 PCH: Remove feature filter from Smart Linking
  src/content-helper/common/class-content-helper-feature.php
  src/content-helper/editor-sidebar/smart-linking/class-smart-linking.php
Labels: Changelog: Removed

#2609 PCH Excerpt Generator: Improve error handling
  build/content-helper/dashboard-widget.asset.php
  build/content-helper/dashboard-widget.js
  build/content-helper/editor-sidebar.asset.php
  build/content-helper/editor-sidebar.js
  build/content-helper/excerpt-generator.asset.php
  build/content-helper/excerpt-generator.js
  src/content-helper/common/base-provider.tsx
  src/content-helper/excerpt-generator/components/excerpt-panel.tsx
  src/content-helper/excerpt-generator/provider.ts
Labels: Changelog: Fixed

#2610 PCH: Fix potential fatal with `enqueue_settings_assets` strict parameter
  src/UI/class-settings-page.php
Labels: Changelog: Fixed

#2612 Fix some untranslatable strings
  build/blocks/recommendations/edit.asset.php
  build/blocks/recommendations/edit.js
  build/content-helper/excerpt-generator.asset.php
  build/content-helper/excerpt-generator.js
  src/blocks/recommendations/components/parsely-recommendations-inspector-controls.tsx
  src/content-helper/excerpt-generator/components/excerpt-panel.tsx
Labels: Type: Maintenance, Changelog: Fixed

#2650 PCH Smart Linking: Use the post title as the Smart Link title.
  src/Models/class-smart-link.php
Labels: Changelog: Changed

#2656 Fix failing E2E tests
  tests/e2e/specs/content-helper/top-bar-icon.spec.ts
  tests/e2e/utils.ts
Labels: Type: Maintenance

#2654 PCH Smart Linking: Show error when API returns empty list of Smart Link suggestions
  build/content-helper/editor-sidebar.asset.php
  build/content-helper/editor-sidebar.js
  src/content-helper/editor-sidebar/smart-linking/component.tsx
Labels: Changelog: Fixed

#2657 Update Smart Linking screenshot
  .wordpress-org/screenshot-4.png
Labels: Type: Maintenance

#2655 PCH Performance Stats: Remove UTM parameters from the 'View in Parse.ly' button
  src/class-dashboard-link.php
  src/content-helper/editor-sidebar/class-editor-sidebar.php
Labels: Changelog: Fixed

#2662 PCH Smart Linking: Fix bug causing ‘No smart links’ error despite valid API response
  build/content-helper/editor-sidebar.asset.php
  build/content-helper/editor-sidebar.js
  src/content-helper/editor-sidebar/smart-linking/component.tsx
Labels: Changelog: Fixed

#2663 Permissions: Add filter to override default permissions for PCH features
  src/class-permissions.php
Labels: Changelog: Added

#2665 Add .stylelintrc
  .stylelintrc
  src/content-helper/common/css/common.scss
  src/content-helper/dashboard-widget/dashboard-widget.scss
  src/content-helper/editor-sidebar/editor-sidebar.scss
  src/content-helper/editor-sidebar/performance-stats/performance-stats.scss
  src/content-helper/editor-sidebar/related-posts/related-posts.scss
  src/content-helper/editor-sidebar/smart-linking/smart-linking.scss
  src/content-helper/editor-sidebar/title-suggestions/title-suggestions.scss
  src/css/admin-settings.scss
  src/css/recommended-widget.scss
Labels: Type: Maintenance

#2664 ESLint: Use method-signature-style rule
  .eslintrc
  src/@types/gutenberg/types.ts
Labels: Type: Maintenance

#2666 PCH Related Posts: Prevent Related Posts indefinite loading
  build/content-helper/editor-sidebar.asset.php
  build/content-helper/editor-sidebar.js
  src/content-helper/editor-sidebar/related-posts/hooks.ts
Labels: Changelog: Fixed

#2668 Fix deprecation warnings in the browser console in WordPress 6.6
  build/content-helper/editor-sidebar.asset.php
  build/content-helper/editor-sidebar.js
  build/content-helper/excerpt-generator.asset.php
  build/content-helper/excerpt-generator.js
  src/@types/gutenberg/wrapper.ts
  src/content-helper/editor-sidebar/editor-sidebar.tsx
  src/content-helper/excerpt-generator/components/excerpt-panel.tsx
Labels: Type: Maintenance, Changelog: Fixed

#2671 Add Excerpt Suggestions integration tests
  tests/Integration/content-helper/ContentHelperExcerptSuggestionsTest.php
Labels: Type: Maintenance

#2672 Add Content Helper options integration tests
  tests/Integration/OptionsTest.php
Labels: Type: Maintenance

#2673 PCH Smart Linking: Prevent suggesting links in unexpected blocks
  build/content-helper/editor-sidebar-rtl.css
  build/content-helper/editor-sidebar.asset.php
  build/content-helper/editor-sidebar.css
  build/content-helper/editor-sidebar.js
  src/@types/assets/window.d.ts
  src/content-helper/editor-sidebar/smart-linking/class-smart-linking.php
  src/content-helper/editor-sidebar/smart-linking/component-settings.tsx
  src/content-helper/editor-sidebar/smart-linking/component.tsx
  src/content-helper/editor-sidebar/smart-linking/smart-linking.scss
  src/content-helper/editor-sidebar/smart-linking/smart-linking.tsx
  src/content-helper/editor-sidebar/smart-linking/utils.ts
  wp-parsely.php
Labels: Changelog: Fixed

#2675 Fix PHPStan error
  src/Endpoints/class-base-api-proxy.php
Labels: Type: Maintenance
