Repository Parsely/wp-parsely, pull requests merged in 2024-05, with the labels that each got.

#2436 PCH Smart Linking: Fix removal of existing Smart Links on subsequent runs
  build/content-helper/editor-sidebar.asset.php
  build/content-helper/editor-sidebar.js
  src/content-helper/editor-sidebar/smart-linking/component.tsx
Labels: Changelog: Fixed, Feature: Content Helper

#2432 PCH Related Posts: Fix hang under edge cases
  build/content-helper/editor-sidebar.asset.php
  build/content-helper/editor-sidebar.css
  build/content-helper/editor-sidebar.js
  src/content-helper/editor-sidebar/related-posts/component-filter-settings.tsx
  src/content-helper/editor-sidebar/related-posts/component.tsx
  src/content-helper/editor-sidebar/related-posts/hooks.ts
  src/content-helper/editor-sidebar/related-posts/related-posts.scss
  tests/js/content-helper/structure.test.tsx
Labels: Type: Maintenance, Changelog: Fixed, Feature: Content Helper

#2465 Merge trunk into develop after the wp-parsely 3.14.4 release
  CHANGELOG.md
  README.md
  build/content-helper/editor-sidebar.asset.php
  build/content-helper/editor-sidebar.css
  build/content-helper/editor-sidebar.js
  package-lock.json
  package.json
  src/content-helper/editor-sidebar/related-posts/component-filter-settings.tsx
  src/content-helper/editor-sidebar/related-posts/component.tsx
  src/content-helper/editor-sidebar/related-posts/hooks.ts
  src/content-helper/editor-sidebar/related-posts/related-posts.scss
  src/content-helper/editor-sidebar/smart-linking/component.tsx
  tests/e2e/utils.ts
  tests/js/content-helper/structure.test.tsx
  wp-parsely.php
Labels: Type: Maintenance

#2467 Fix: Make PCH Related Posts filters work for non-admins
  build/content-helper/editor-sidebar.asset.php
  build/content-helper/editor-sidebar.js
  src/content-helper/editor-sidebar/related-posts/component.tsx
  src/content-helper/editor-sidebar/related-posts/hooks.ts
Labels: Changelog: Fixed, Feature: Content Helper

#2473 Manually update npm dependencies
  build/blocks/recommendations/edit.asset.php
  build/blocks/recommendations/edit.js
  build/blocks/recommendations/view.asset.php
  build/blocks/recommendations/view.js
  build/content-helper/dashboard-widget.asset.php
  build/content-helper/dashboard-widget.js
  build/content-helper/editor-sidebar.asset.php
  build/content-helper/editor-sidebar.css
  build/content-helper/editor-sidebar.js
  build/content-helper/excerpt-generator.asset.php
  build/content-helper/excerpt-generator.js
  build/recommended-widget.asset.php
  build/recommended-widget.css
  build/telemetry.asset.php
  build/telemetry.js
  package-lock.json
  package.json
  tests/e2e/specs/content-helper/related-posts-panel-filters.spec.ts
  tests/e2e/utils.ts
Labels: Type: Maintenance, Component: Dependencies, javascript

#2475 Update minimum node and npm versions
  .nvmrc
  package-lock.json
  package.json
Labels: Type: Maintenance

#2474 phpstan.neon: Replace deprecated setting
  phpstan.neon
Labels: Type: Maintenance

#2508 PCH Smart Linking: Remove Link Length option from the UI
  build/content-helper/editor-sidebar.asset.php
  build/content-helper/editor-sidebar.js
  src/content-helper/common/settings/types/sidebar-settings.d.ts
  src/content-helper/editor-sidebar/editor-sidebar.tsx
  src/content-helper/editor-sidebar/smart-linking/component-settings.tsx
  src/content-helper/editor-sidebar/smart-linking/component.tsx
  src/content-helper/editor-sidebar/smart-linking/provider.ts
  src/content-helper/editor-sidebar/smart-linking/smart-linking.tsx
  src/content-helper/editor-sidebar/smart-linking/store.ts
Labels: Changelog: Changed

#2506 PCH Excerpt Generator: Allow editing when reviewing
  build/content-helper/excerpt-generator-rtl.css
  build/content-helper/excerpt-generator.asset.php
  build/content-helper/excerpt-generator.css
  build/content-helper/excerpt-generator.js
  src/content-helper/excerpt-generator/components/excerpt-panel.tsx
  src/content-helper/excerpt-generator/excerpt-generator.scss
Labels: Changelog: Changed, Feature: Content Helper

#2504 package.json: Remove unneeded override
  package-lock.json
  package.json
Labels: Type: Maintenance, Component: Dependencies, javascript
