Repository Parsely/wp-parsely, pull requests merged in 2024-01, with the labels that each got.

#2094 Settings Page: Improve "Disable JavaScript" help text
  src/UI/class-settings-page.php
Labels: Changelog: Changed

#2091 Content Helper Dashboard Widget: Remember settings
  build/content-helper/dashboard-widget.asset.php
  build/content-helper/dashboard-widget.js
  phpunit-integration.xml.dist
  src/@types/assets/window.d.ts
  src/Endpoints/class-base-endpoint.php
  src/Endpoints/user-meta/class-base-endpoint-user-meta.php
  src/Endpoints/user-meta/class-dashboard-widget-settings-endpoint.php
  src/content-helper/dashboard-widget/class-dashboard-widget.php
  src/content-helper/dashboard-widget/components/top-posts.tsx
  src/content-helper/dashboard-widget/dashboard-widget.tsx
  wp-parsely.php
Labels: Changelog: Added, Feature: Content Helper

#2110 Update rector level set list to PHP 7.2
  rector.php
Labels: Type: Maintenance

#2108 Fix untranslatable string
  build/content-helper/editor-sidebar.asset.php
  build/content-helper/editor-sidebar.js
  src/content-helper/editor-sidebar/title-suggestions/component.tsx
Labels: Type: Maintenance, Changelog: Changed

#2113 Update README.md and screenshots
  .wordpress-org/screenshot-1.png
  .wordpress-org/screenshot-10.png
  .wordpress-org/screenshot-11.png
  .wordpress-org/screenshot-2.png
  .wordpress-org/screenshot-3.png
  .wordpress-org/screenshot-4.png
  .wordpress-org/screenshot-5.png
  .wordpress-org/screenshot-6.png
  .wordpress-org/screenshot-7.png
  .wordpress-org/screenshot-8.png
  .wordpress-org/screenshot-9.png
  README.md
Labels: Type: Maintenance

#2106 Content Helper Editor Sidebar: Remember settings
  build/content-helper/dashboard-widget.asset.php
  build/content-helper/dashboard-widget.js
  build/content-helper/editor-sidebar.asset.php
  build/content-helper/editor-sidebar.js
  src/Endpoints/user-meta/class-base-endpoint-user-meta.php
  src/Endpoints/user-meta/class-dashboard-widget-settings-endpoint.php
  src/Endpoints/user-meta/class-editor-sidebar-settings-endpoint.php
  src/content-helper/common/class-content-helper-feature.php
  src/content-helper/common/components/persona-selector/component.tsx
  src/content-helper/common/components/persona-selector/index.ts
  src/content-helper/common/components/tone-selector/component.tsx
  src/content-helper/common/components/tone-selector/index.ts
  src/content-helper/common/hooks/useSaveSettings.ts
  src/content-helper/dashboard-widget/class-dashboard-widget.php
  src/content-helper/dashboard-widget/components/top-posts.tsx
  src/content-helper/editor-sidebar/class-editor-sidebar.php
  src/content-helper/editor-sidebar/editor-sidebar.tsx
  src/content-helper/editor-sidebar/related-top-posts/component-list.tsx
  src/content-helper/editor-sidebar/title-suggestions/component-settings.tsx
  src/content-helper/editor-sidebar/title-suggestions/component.tsx
  src/content-helper/editor-sidebar/title-suggestions/store.ts
  tests/Integration/Endpoints/DashboardWidgetSettingsEndpointTest.php
  tests/e2e/utils.ts
  tests/js/content-helper/structure.test.tsx
  wp-parsely.php
Labels: Changelog: Added, Feature: Content Helper

#2114 Make props passed to functions read-only
  src/blocks/recommendations/components/parsely-recommendations-fetcher.tsx
  src/content-helper/common/components/beta-badge/component.tsx
  src/content-helper/common/components/persona-selector/component.tsx
  src/content-helper/common/components/tone-selector/component.tsx
  src/content-helper/dashboard-widget/components/top-posts.tsx
  src/content-helper/editor-sidebar/title-suggestions/component-settings.tsx
  src/content-helper/editor-sidebar/title-suggestions/component-title-suggestion.tsx
Labels: Type: Maintenance

#2115 Content Helper Dashboard Widget: Improve settings system
  build/content-helper/dashboard-widget.asset.php
  build/content-helper/dashboard-widget.js
  src/Endpoints/user-meta/class-dashboard-widget-settings-endpoint.php
  src/content-helper/dashboard-widget/components/top-posts.tsx
  src/content-helper/dashboard-widget/dashboard-widget.tsx
  src/content-helper/dashboard-widget/provider.ts
  tests/Integration/Endpoints/DashboardWidgetSettingsEndpointTest.php
Labels: Type: Maintenance, Feature: Content Helper

#2111 Allow remote requests to Parse.ly in controlled environments
  src/Utils/utils.php
  src/class-parsely.php
Labels: Changelog: Fixed

#2121 Fix PHPStan error in utils.php
  src/Utils/utils.php
Labels: Type: Maintenance

#2122 PCH Title Suggestions: Remove tone and persona from store
  build/content-helper/editor-sidebar.asset.php
  build/content-helper/editor-sidebar.js
  src/content-helper/editor-sidebar/title-suggestions/component.tsx
  src/content-helper/editor-sidebar/title-suggestions/store.ts
Labels: Type: Maintenance

#2119 Fix singular translation issues & accessibility improvements
  build/content-helper/dashboard-widget.asset.php
  build/content-helper/dashboard-widget.js
  build/content-helper/editor-sidebar.asset.php
  build/content-helper/editor-sidebar.js
  src/content-helper/common/utils/constants.ts
  src/content-helper/common/utils/post.tsx
  src/content-helper/dashboard-widget/components/top-posts.tsx
Labels: Changelog: Fixed

#2130 Update wp-parsely version number to 3.13.0
  README.md
  package-lock.json
  package.json
  tests/e2e/utils.ts
  wp-parsely.php
Labels: Type: Maintenance

#2141 Fix failing E2E test
  tests/e2e/specs/content-helper/related-top-posts-panel-filters.spec.ts
Labels: Type: Maintenance

#2142 Content Helper: Fix blank Dashboard Widget on older WordPress versions
  build/content-helper/dashboard-widget.asset.php
  build/content-helper/dashboard-widget.js
  src/content-helper/dashboard-widget/dashboard-widget.tsx
Labels: Changelog: Fixed

#2147 PCH Excerpt Generator: Fix persistent notification
  build/content-helper/excerpt-generator.asset.php
  build/content-helper/excerpt-generator.js
  src/content-helper/excerpt-generator/components/excerpt-panel.tsx
Labels: Changelog: Fixed, Feature: Content Helper

#2148 Update Readme links
  README.md
Labels: Type: Maintenance

#2149 Update README.md
  README.md
Labels: Type: Maintenance

#2131 PCH Smart Linking: Implement settings system
  build/content-helper/editor-sidebar.asset.php
  build/content-helper/editor-sidebar.js
  src/Endpoints/user-meta/class-editor-sidebar-settings-endpoint.php
  src/content-helper/editor-sidebar/cross-linker/component-settings.tsx
  src/content-helper/editor-sidebar/cross-linker/component.tsx
  src/content-helper/editor-sidebar/cross-linker/cross-linker.tsx
  src/content-helper/editor-sidebar/cross-linker/store.ts
  src/content-helper/editor-sidebar/editor-sidebar.tsx
  src/content-helper/editor-sidebar/title-suggestions/component.tsx
  tests/Integration/Endpoints/EditorSidebarSettingsEndpointTest.php
Labels: Feature: Content Helper
