Repository Parsely/wp-parsely, pull requests merged in 2025-01, with the labels that each got.

#3029 Add a simple linter and a pre-commit hook for it
  .husky/pre-commit
  CHANGELOG.md
  lint.php
  src/@types/assets/window.d.ts
  src/Telemetry/Tracks/class-tracks-pixel.php
  src/content-helper/common/class-content-helper-feature.php
  src/content-helper/common/components/input-range/style.scss
  src/content-helper/editor-sidebar/performance-stats/performance-stats.scss
  src/content-helper/editor-sidebar/related-posts/related-posts.scss
  src/rest-api/content-helper/class-endpoint-smart-linking.php
  src/rest-api/settings/class-base-settings-endpoint.php
  src/services/class-base-api-service.php
  src/services/content-api/endpoints/class-endpoint-analytics-posts.php
  tests/Integration/ContentHelper/ContentHelperPostListStatsTest.php
  tests/Integration/RestAPI/BaseAPIControllerTest.php
  tests/Integration/RestAPI/ContentHelper/ContentHelperFeatureTestTrait.php
  tests/Integration/UI/SettingsPageTest.php
  wp-parsely.php
Labels: Type: Maintenance

#3030 Dedupe package-lock.json
  package-lock.json
Labels: Type: Maintenance

#3066 PCH: Remove beta messaging
  build/content-helper/editor-sidebar-rtl.css
  build/content-helper/editor-sidebar.asset.php
  build/content-helper/editor-sidebar.css
  build/content-helper/editor-sidebar.js
  src/content-helper/editor-sidebar/excerpt-suggestions/component-panel.tsx
  src/content-helper/editor-sidebar/excerpt-suggestions/excerpt-suggestions.scss
  src/content-helper/editor-sidebar/smart-linking/smart-linking.tsx
  src/content-helper/editor-sidebar/tabs/sidebar-tools-tab.tsx
Labels: Changelog: Changed, Feature: PCH

#3007 Add identifier to JSON-LD metadata
  src/Metadata/class-metadata-renderer.php
  tests/Integration/Endpoints/RestMetadataTest.php
  tests/Integration/UI/MetadataRendererTest.php
  tests/e2e/specs/front-end-metadata.spec.ts
Labels: Changelog: Added

#3090 Traffic Boost: Fix permalinks and highlighting
  build/content-helper/dashboard-page.asset.php
  build/content-helper/dashboard-page.js
  src/UI/class-dashboard-page.php
  src/content-helper/common/base-wordpress-provider.tsx
  src/content-helper/dashboard-page/pages/traffic-boost/preview/components/link-options-panel.tsx
  src/content-helper/dashboard-page/pages/traffic-boost/preview/components/preview-iframe.tsx
  src/content-helper/dashboard-page/pages/traffic-boost/preview/components/text-selection-tooltip.tsx
  src/content-helper/dashboard-page/pages/traffic-boost/preview/preview-post.php
  src/content-helper/dashboard-page/pages/traffic-boost/preview/preview.tsx
  src/content-helper/dashboard-page/pages/traffic-boost/preview/utils.ts
  src/content-helper/dashboard-page/pages/traffic-boost/provider.ts
Labels: Component: PHP, Component: JavaScript, Feature: PCH, Feature: Traffic Boost

#3092 Fix update metadata endpoint calling issues
  src/UI/class-settings-page.php
  src/class-parsely.php
  tests/Integration/CallUpdateMetadataEndpointTest.php
Labels: Type: Maintenance, Changelog: Fixed

#3093 Screenshots: Remove PCH beta messaging
  .wordpress-org/screenshot-3.png
  .wordpress-org/screenshot-4.png
  .wordpress-org/screenshot-5.png
  .wordpress-org/screenshot-7.png
Labels: Type: Maintenance, Feature: PCH

#3095 PCH: Fix issue with potential duplicate API calls in settings and smart links
  build/content-helper/dashboard-widget.asset.php
  build/content-helper/dashboard-widget.js
  build/content-helper/editor-sidebar.asset.php
  build/content-helper/editor-sidebar.js
  src/content-helper/common/settings/provider.tsx
  src/content-helper/editor-sidebar/smart-linking/component.tsx
  src/rest-api/settings/class-endpoint-excerpt-suggestions-settings.php
Labels: Changelog: Fixed, Feature: PCH
