Repository Parsely/wp-parsely, pull requests merged in 2025-04, with the labels that each got.

#3216 Smart Links: Add functionality context to ITM parameters
  build/content-helper/editor-sidebar.asset.php
  build/content-helper/editor-sidebar.js
  src/Models/class-smart-link.php
  src/content-helper/editor-sidebar/smart-linking/utils.ts
  src/rest-api/content-helper/class-endpoint-smart-linking.php
  src/rest-api/content-helper/class-endpoint-traffic-boost.php
  tests/Integration/RestAPI/ContentHelper/EndpointSmartLinkingTest.php
Labels: Feature: PCH, Feature: PCH Traffic Boost

#3242 GitHub Issue Templates: Adjust labels
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/release-template-new.md
  .github/ISSUE_TEMPLATE/release-template.md
Labels: Maintenance

#3245 dependabot.yml: Customize dependabot labels
  .github/dependabot.yml
Labels: Maintenance

#3246 Changelog: Add "Breaking Changes" section
  bin/release.php
Labels: Maintenance

#3250 Improve release workflow
  .github/workflows/bump-version.yml
  .github/workflows/release-plugin.yml
  src/content-helper/editor-sidebar/class-editor-sidebar.php
Labels: Maintenance

#3275 GitHub Workflows: Update Ubuntu to v24.04 LTS
  .github/workflows/build-plugin.yml
  .github/workflows/bump-version.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/cs-lint.yml
  .github/workflows/dependency-review.yml
  .github/workflows/deploy.yml
  .github/workflows/integration-tests.yml
  .github/workflows/node.js.yml
  .github/workflows/release-plugin.yml
  .github/workflows/unit-tests.yml
Labels: Maintenance

#3249 Fix "Related Posts" persistence when sidebar is closed
  build/content-helper/editor-sidebar.asset.php
  build/content-helper/editor-sidebar.js
  src/content-helper/editor-sidebar/related-posts/component.tsx
  src/content-helper/editor-sidebar/related-posts/store.ts
  tests/js/content-helper/structure.test.tsx
Labels: Feature: PCH

#3274 README.md: Update "Tested up to" to 6.8
  README.md
Labels: Maintenance

#3273 release.php: Update dependencies label
  CHANGELOG.md
  bin/release.php
Labels: Maintenance

#3276 Update testing workflows
  .github/workflows/e2e-tests.yml
  .github/workflows/integration-tests.yml
  .github/workflows/unit-tests.yml
  .nvmrc
Labels: Maintenance

#3278 Update screenshots for 3.18 release
  .wordpress-org/screenshot-3.png
  .wordpress-org/screenshot-4.png
  .wordpress-org/screenshot-5.png
  .wordpress-org/screenshot-6.png
  .wordpress-org/screenshot-7.png
  .wordpress-org/screenshot-8.png
Labels: Maintenance

#3285 Dedupe package-lock.json
  package-lock.json
Labels: Maintenance, Deps: JavaScript, Deps

#3286 Remove outdated GitHub release issue template
  .github/ISSUE_TEMPLATE/release-template-new.md
  .github/ISSUE_TEMPLATE/release-template.md
Labels: Maintenance
