Repository Parsely/wp-parsely, pull requests merged in 2025-05, with the labels that each got.

#3322 Fix link text selection adjustment when a link is included later in the same parent
  build/content-helper/dashboard-page.asset.php
  build/content-helper/dashboard-page.js
  src/content-helper/dashboard-page/pages/traffic-boost/preview/components/text-selection-tooltip.tsx
Labels: Maintenance

#3325 Do not return Traffic Boost sample settings
  src/UI/class-dashboard-page.php
  src/rest-api/content-helper/class-endpoint-traffic-boost.php
  src/rest-api/settings/class-endpoint-traffic-boost-settings.php
  src/services/suggestions-api/endpoints/class-endpoint-suggest-inbound-link-positions.php
  src/services/suggestions-api/endpoints/class-endpoint-suggest-inbound-links.php
Labels: Maintenance, Feature: Traffic Boost, Feature: Dashboard Page

#3324 Fix corrupt Traffic Boost option when upgrading
  src/class-parsely.php
  tests/Integration/OptionsTest.php
Labels: Maintenance, Feature: Traffic Boost

#3327 Remove Parse.ly Dashboard page from UI
  build/content-helper/dashboard-page.asset.php
  build/content-helper/dashboard-page.js
  src/UI/class-dashboard-page.php
  src/content-helper/dashboard-page/dashboard-page.tsx
  src/content-helper/dashboard-page/pages/traffic-boost/page-component.tsx
Labels: Maintenance, Feature: Dashboard Page

#3328 Make the Parse.ly menu dynamic
  src/UI/class-dashboard-page.php
  src/UI/class-settings-page.php
Labels: Maintenance, Feature: Dashboard Page

#3329 Update traffic boost footer UI
  build/content-helper/dashboard-page-rtl.css
  build/content-helper/dashboard-page.asset.php
  build/content-helper/dashboard-page.css
  build/content-helper/dashboard-page.js
  src/content-helper/dashboard-page/pages/traffic-boost/preview/components/preview-footer.tsx
  src/content-helper/dashboard-page/pages/traffic-boost/preview/components/preview-header.tsx
  src/content-helper/dashboard-page/pages/traffic-boost/preview/preview-post.php
  src/content-helper/dashboard-page/pages/traffic-boost/preview/preview.scss
  src/content-helper/dashboard-page/pages/traffic-boost/preview/preview.tsx
  src/content-helper/dashboard-page/pages/traffic-boost/sidebar/components/tabs/suggestions-tab.tsx
Labels: Maintenance, Feature: Traffic Boost

#3330 Traffic boost UI label updates and regenerate button removal
  build/content-helper/dashboard-page-rtl.css
  build/content-helper/dashboard-page.asset.php
  build/content-helper/dashboard-page.css
  build/content-helper/dashboard-page.js
  build/content-helper/editor-sidebar.asset.php
  build/content-helper/editor-sidebar.js
  src/Models/class-inbound-smart-link.php
  src/content-helper/dashboard-page/pages/traffic-boost/preview/components/link-counter.tsx
  src/content-helper/dashboard-page/pages/traffic-boost/preview/components/preview-footer.tsx
  src/content-helper/dashboard-page/pages/traffic-boost/preview/hooks/use-iframe-highlight.ts
  src/content-helper/dashboard-page/pages/traffic-boost/preview/preview.tsx
  src/content-helper/dashboard-page/pages/traffic-boost/sidebar/components/add-new-link-button.tsx
  src/content-helper/dashboard-page/pages/traffic-boost/sidebar/components/post-details.tsx
  src/content-helper/dashboard-page/pages/traffic-boost/sidebar/components/tabs/suggestions-tab.tsx
  src/content-helper/dashboard-page/pages/traffic-boost/sidebar/sidebar.scss
  src/content-helper/dashboard-page/pages/traffic-boost/sidebar/sidebar.tsx
  src/content-helper/editor-sidebar/smart-linking/component.tsx
  src/content-helper/editor-sidebar/smart-linking/hooks.ts
  src/content-helper/editor-sidebar/smart-linking/review-modal/component-modal.tsx
  src/rest-api/content-helper/class-endpoint-smart-linking.php
  src/rest-api/content-helper/class-endpoint-traffic-boost.php
Labels: Feature: Traffic Boost

#3331 Fix PHPStan error
  src/Models/class-smart-link.php
Labels: Maintenance

#3332 Fix traffic boost suggestion cache refresh
  src/Models/class-inbound-smart-link.php
  src/Models/class-smart-link.php
Labels: Feature: Traffic Boost

#3333 Fix reference to Pendo class
  src/Telemetry/telemetry-init.php
Labels: Maintenance

#3335 Hide Traffic Boost submenu when API Secret is not set
  src/UI/class-dashboard-page.php
Labels: Feature: Traffic Boost

#3338 Fix "Add Source Link" cursor
  build/content-helper/dashboard-page-rtl.css
  build/content-helper/dashboard-page.asset.php
  build/content-helper/dashboard-page.css
  src/content-helper/dashboard-page/pages/traffic-boost/sidebar/sidebar.scss
Labels: Feature: PCH, Feature: Traffic Boost

#3337 Traffic Boost: Improve error handling
  build/content-helper/dashboard-page.asset.php
  build/content-helper/dashboard-page.js
  src/content-helper/common/content-helper-error.tsx
  src/content-helper/common/providers/stats-provider.tsx
  src/content-helper/dashboard-page/components/posts-table/component.tsx
  src/content-helper/dashboard-page/pages/traffic-boost/provider.ts
  src/content-helper/dashboard-page/pages/traffic-boost/sidebar/components/tabs-content.tsx
  src/content-helper/dashboard-page/pages/traffic-boost/sidebar/sidebar.tsx
  src/content-helper/dashboard-page/pages/traffic-boost/single-post-component.tsx
Labels: Feature: PCH, Feature: Traffic Boost

#3342 Minor fixes to tab visibility for accessibility
  build/content-helper/dashboard-page-rtl.css
  build/content-helper/dashboard-page.asset.php
  build/content-helper/dashboard-page.css
  build/content-helper/dashboard-page.js
  src/content-helper/dashboard-page/pages/traffic-boost/sidebar/components/links-list/links-list.scss
  src/content-helper/dashboard-page/pages/traffic-boost/sidebar/components/links-list/single-link.tsx
  src/content-helper/dashboard-page/pages/traffic-boost/sidebar/sidebar.scss
Labels: Feature: PCH, Feature: Traffic Boost

#3341 Settings page: Add Content Helper messages
  build/admin-settings-rtl.css
  build/admin-settings.asset.php
  build/admin-settings.css
  build/admin-settings.js
  phpstan.neon
  src/UI/class-settings-page.php
  src/content-helper/common/providers/check-auth-provider.ts
  src/css/admin-settings.scss
  src/js/admin-settings.ts
  src/rest-api/content-helper/class-content-helper-controller.php
  src/rest-api/content-helper/class-endpoint-check-auth.php
  src/services/suggestions-api/class-suggestions-api-service.php
  src/services/suggestions-api/endpoints/class-endpoint-check-auth.php
  tests/Integration/RestAPI/ContentHelper/ContentHelperControllerTest.php
Labels: Changelog: Added

#3351 Make some caching checks more flexible
  src/Models/class-inbound-smart-link.php
  src/Models/class-smart-link.php
  src/Utils/class-utils.php
Labels: Changelog: Fixed

#3379 Fix update-version.sh
  bin/update-version.sh
Labels: Maintenance
