Repository Parsely/wp-parsely, pull requests merged in 2025-06, with the labels that each got.

#3414 Fix PHPStan errors on PHP 8.3 and above
  phpstan.neon
Labels: Maintenance

#3416 PHPStan: Fix error preventing Bleeding Edge mode
  tests/Unit/Utils/UtilsTest.php
Labels: Maintenance

#3396 release-template.md: Include GitHub milestone link
  .github/ISSUE_TEMPLATE/release-template.md
Labels: Maintenance

#3443 Dedupe package-lock.json
  package-lock.json
Labels: Maintenance, Deps: JavaScript, Deps

#3442 Update minimum node/npm version
  .nvmrc
  docs/CONTRIBUTING.md
  package-lock.json
  package.json
Labels: Maintenance

#3444 Update Suggestions API base URL
  src/services/suggestions-api/class-suggestions-api-service.php
  src/services/suggestions-api/endpoints/class-endpoint-suggest-brief.php
  src/services/suggestions-api/endpoints/class-endpoint-suggest-headline.php
  src/services/suggestions-api/endpoints/class-endpoint-suggest-inbound-link-positions.php
  src/services/suggestions-api/endpoints/class-endpoint-suggest-inbound-links.php
  src/services/suggestions-api/endpoints/class-endpoint-suggest-linked-reference.php
  src/services/suggestions-api/endpoints/class-suggestions-api-base-endpoint.php
Labels: Maintenance

#3464 Update Traffic Boost screenshot
  .wordpress-org/screenshot-3.png
Labels: Maintenance

#3489 Update "Content Helper" to "Content Intelligence" on settings page
  src/UI/class-settings-page.php
  tests/e2e/specs/activation-flow.spec.ts
Labels: Changelog: Changed, Feature: Traffic Boost, wp-parsely
